export const CategoriesTopMenu: CategoriesMenu[] = [
	{
		name: "Hot Games",
		descriptions:
			"Kami hadirkan Hotgame dengan provider pilihan yang kami pilihkan untuk pelanggan setia kami dari jenis permainan sport, casino, slot serta arcade game. Nikmati pilihan2 game terbaik yang kami sediakan untuk anda.",
		alias: "Hot Games",
		slug: "hot-games",
		icon: "/images/categories/hot-games.svg",
		cover: "/images/categories/hot-games-cover.webp",
		cover_small: "/images/categories/hot-games-cover-small.webp",
		style: {
			bg_gradient: "hero-background-purple",
			glow_effect_1: "glow-effect-purple",
			glow_effect_2: "glow-effect-purple-2",
			her0_image: "hero-image-purple",
		},
		sub: [
			{
				name: "Pragmatic Play",
				slug: "pragmatic",
				category: "slots",
				icon: "/images/sub-categories/game-code-7.webp",
				cover: "/images/sub-categories/game-code-7-cover.webp",
				link: "/slots?p=pragmatic",
				alternative_link: "/slots/pragmatic",
			},
			{
				name: "Nex4D",
				slug: "nex-4d",
				category: "others",
				icon: "/images/sub-categories/game-code-48.webp",
				cover: "/images/sub-categories/game-code-48-cover.webp",
				link: "javascript:openNewTab('/dispatch/game/BALAK4D/Desktop', 'Main')",
				alternative_link: "/others/nex-4d",
			},
			{
				name: "JILI",
				slug: "jili",
				category: "slots",
				icon: "/images/sub-categories/game-code-70.webp",
				cover: "/images/sub-categories/game-code-70-cover.webp",
				link: "/slots?p=jili",
				alternative_link: "/slots/jili",
			},
			{
				name: "Habanero",
				slug: "habanero",
				category: "slots",
				icon: "/images/sub-categories/game-code-16.webp",
				cover: "/images/sub-categories/game-code-16-cover.webp",
				link: "/slots?p=habanero",
				alternative_link: "/slots/habanero",
			},
			{
				name: "Microgaming",
				slug: "microgaming",
				category: "slots",
				icon: "/images/sub-categories/game-code-17.webp",
				cover: "/images/sub-categories/game-code-17-cover.webp",
				link: "/slots?p=microgaming",
				alternative_link: "/slots/microgaming",
			},
			{
				name: "PG SOFT",
				slug: "pg-soft",
				category: "slots",
				icon: "/images/sub-categories/game-code-9.webp",
				cover: "/images/sub-categories/game-code-9-cover.webp",
				link: "/slots?p=pg-soft",
				alternative_link: "/slots/pg-soft",
			},
			{
				name: "No Limit City",
				slug: "no-limit-city",
				category: "slots",
				icon: "/images/sub-categories/game-code-92.webp",
				cover: "/images/sub-categories/game-code-92-cover.webp",
				link: "/slots?p=no-limit-city",
				alternative_link: "/slots/no-limit-city",
			},
			{
				name: "Hacksaw",
				slug: "hacksaw",
				category: "slots",
				icon: "/images/sub-categories/game-code-98.webp",
				cover: "/images/sub-categories/game-code-98-cover.webp",
				link: "/slots?p=hacksaw",
				alternative_link: "/slots/hacksaw",
			},
			{
				name: "Playstart",
				slug: "playstart",
				category: "slots",
				icon: "/images/sub-categories/game-code-65.webp",
				cover: "/images/sub-categories/game-code-65-cover.webp",
				link: "/slots?p=playstart",
				alternative_link: "/slots/playstart",
			},
		],
	},
	{
		name: "Slots",
		descriptions:
			"Kami hadirkan Slots dengan provider pilihan yang kami pilihkan untuk pelanggan setia kami dari jenis permainan sport, casino, slot serta arcade game. Nikmati pilihan2 game terbaik yang kami sediakan untuk anda.",
		alias: "Slots Games",
		slug: "slots",
		icon: "/images/categories/slots.svg",
		cover: "/images/categories/slots-cover.webp",
		cover_small: "/images/categories/slots-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "Pragmatic Play",
				slug: "pragmatic",
				category: "slots",
				icon: "/images/sub-categories/game-code-7.webp",
				cover: "/images/sub-categories/game-code-7.webp",
				link: "/slots?p=pragmatic",
				alternative_link: "/slots/pragmatic",
			},
			{
				name: "PG Soft",
				slug: "pgsoft",
				category: "slots",
				icon: "/images/sub-categories/game-code-9.webp",
				cover: "/images/sub-categories/game-code-9.webp",
				link: "/slots?p=pgsoft",
				alternative_link: "/slots/pgsoft",
			},
			{
				name: "Slot88 x PP",
				slug: "slot88",
				category: "slots",
				icon: "/images/sub-categories/game-code-40.webp",
				cover: "/images/sub-categories/game-code-40.webp",
				link: "/slots?p=slot88",
				alternative_link: "/slots/slot88",
			},
			{
				name: "Hacksaw",
				slug: "hacksaw",
				category: "slots",
				icon: "/images/sub-categories/game-code-98.webp",
				cover: "/images/sub-categories/game-code-98.webp",
				link: "/slots?p=hacksaw",
				alternative_link: "/slots/hacksaw",
			},
			{
				name: "Fat Panda",
				slug: "fat-panda",
				category: "slots",
				icon: "/images/sub-categories/game-code-112.webp",
				cover: "/images/sub-categories/game-code-112.webp",
				link: "/slots?p=fat-panda",
				alternative_link: "/slots/fat-panda",
			},
			{
				name: "No Limit City",
				slug: "no-limit-city",
				category: "slots",
				icon: "/images/sub-categories/game-code-92.webp",
				cover: "/images/sub-categories/game-code-92.webp",
				link: "/slots?p=no-limit-city",
				alternative_link: "/slots/no-limit-city",
			},
			{
				name: "Jili",
				slug: "jili",
				category: "slots",
				icon: "/images/sub-categories/game-code-70.webp",
				cover: "/images/sub-categories/game-code-70.webp",
				link: "/slots?p=jili",
				alternative_link: "/slots/jili",
			},
			{
				name: "Habanero",
				slug: "habanero",
				category: "slots",
				icon: "/images/sub-categories/game-code-16.webp",
				cover: "/images/sub-categories/game-code-16.webp",
				link: "/slots?p=habanero",
				alternative_link: "/slots/habanero",
			},
			{
				name: "Microgaming",
				slug: "microgaming",
				category: "slots",
				icon: "/images/sub-categories/game-code-17.webp",
				cover: "/images/sub-categories/game-code-17.webp",
				link: "/slots?p=microgaming",
				alternative_link: "/slots/microgaming",
			},
			{
				name: "5GG",
				slug: "fivegg",
				category: "slots",
				icon: "/images/sub-categories/game-code-114.webp",
				cover: "/images/sub-categories/game-code-114.webp",
				link: "/slots?p=fivegg",
				alternative_link: "/slots/fivegg",
			},
			{
				name: "Playtech",
				slug: "playtech",
				category: "slots",
				icon: "/images/sub-categories/game-code-2.webp",
				cover: "/images/sub-categories/game-code-2.webp",
				link: "/slots?p=playtech",
				alternative_link: "/slots/playtech",
			},
			{
				name: "Spade Gaming",
				slug: "spade-gaming",
				category: "slots",
				icon: "/images/sub-categories/game-code-29.webp",
				cover: "/images/sub-categories/game-code-29.webp",
				link: "/slots?p=spade-gaming",
				alternative_link: "/slots/spade-gaming",
			},
			{
				name: "King Midas",
				slug: "king-midas",
				category: "slots",
				icon: "/images/sub-categories/game-code-116.webp",
				cover: "/images/sub-categories/game-code-116.webp",
				link: "/slots?p=king-midas",
				alternative_link: "/slots/king-midas",
			},
			{
				name: "Fast Spin",
				slug: "fast-spin",
				category: "slots",
				icon: "/images/sub-categories/game-code-110.webp",
				cover: "/images/sub-categories/game-code-110.webp",
				link: "/slots?p=fast-spin",
				alternative_link: "/slots/fast-spin",
			},
			{
				name: "VPLUS",
				slug: "vplus",
				category: "slots",
				icon: "/images/sub-categories/game-code-115.webp",
				cover: "/images/sub-categories/game-code-115.webp",
				link: "/slots?p=vplus",
				alternative_link: "/slots/vplus",
			},
			{
				name: "Joker",
				slug: "joker",
				category: "slots",
				icon: "/images/sub-categories/game-code-6.webp",
				cover: "/images/sub-categories/game-code-6.webp",
				link: "/slots?p=joker",
				alternative_link: "/slots/joker",
			},
			{
				name: "Fachai",
				slug: "fachai",
				category: "slots",
				icon: "/images/sub-categories/game-code-72.webp",
				cover: "/images/sub-categories/game-code-72.webp",
				link: "/slots?p=fachai",
				alternative_link: "/slots/fachai",
			},
			{
				name: "AdvantPlay",
				slug: "advantplay",
				category: "slots",
				icon: "/images/sub-categories/game-code-54.webp",
				cover: "/images/sub-categories/game-code-54.webp",
				link: "/slots?p=advantplay",
				alternative_link: "/slots/advantplay",
			},
			{
				name: "Smartsoft",
				slug: "smartsoft",
				category: "slots",
				icon: "/images/sub-categories/game-code-108.webp",
				cover: "/images/sub-categories/game-code-108.webp",
				link: "/slots?p=smartsoft",
				alternative_link: "/slots/smartsoft",
			},
			{
				name: "Naga Games",
				slug: "naga-games",
				category: "slots",
				icon: "/images/sub-categories/game-code-87.webp",
				cover: "/images/sub-categories/game-code-87.webp",
				link: "/slots?p=naga-games",
				alternative_link: "/slots/naga-games",
			},
			{
				name: "JDB",
				slug: "jdb",
				category: "slots",
				icon: "/images/sub-categories/game-code-51.webp",
				cover: "/images/sub-categories/game-code-51.webp",
				link: "/slots?p=jdb",
				alternative_link: "/slots/jdb",
			},
			{
				name: "Playstar",
				slug: "playstar",
				category: "slots",
				icon: "/images/sub-categories/game-code-65.webp",
				cover: "/images/sub-categories/game-code-65.webp",
				link: "/slots?p=playstar",
				alternative_link: "/slots/playstar",
			},
			{
				name: "Spinix",
				slug: "spinix",
				category: "slots",
				icon: "/images/sub-categories/game-code-91.webp",
				cover: "/images/sub-categories/game-code-91.webp",
				link: "/slots?p=spinix",
				alternative_link: "/slots/spinix",
			},
			{
				name: "Crowd Play",
				slug: "crowd-play",
				category: "slots",
				icon: "/images/sub-categories/game-code-73.webp",
				cover: "/images/sub-categories/game-code-73.webp",
				link: "/slots?p=crowd-play",
				alternative_link: "/slots/crowd-play",
			},
			{
				name: "ION Slot",
				slug: "ion-slot",
				category: "slots",
				icon: "/images/sub-categories/game-code-50.webp",
				cover: "/images/sub-categories/game-code-50.webp",
				link: "/slots?p=ion-slot",
				alternative_link: "/slots/ion-slot",
			},
			{
				name: "Bigpot",
				slug: "bigpot",
				category: "slots",
				icon: "/images/sub-categories/game-code-75.webp",
				cover: "/images/sub-categories/game-code-75.webp",
				link: "/slots?p=bigpot",
				alternative_link: "/slots/bigpot",
			},
			{
				name: "VPower",
				slug: "vpower",
				category: "slots",
				icon: "/images/sub-categories/game-code-77.webp",
				cover: "/images/sub-categories/game-code-77.webp",
				link: "/slots?p=vpower",
				alternative_link: "/slots/vpower",
			},
			{
				name: "AMB Slot",
				slug: "amb-slot",
				category: "slots",
				icon: "/images/sub-categories/game-code-61.webp",
				cover: "/images/sub-categories/game-code-61.webp",
				link: "/slots?p=amb-slot",
				alternative_link: "/slots/amb-slot",
			},
			{
				name: "Octoplay",
				slug: "octoplay",
				category: "slots",
				icon: "/images/sub-categories/game-code-109.webp",
				cover: "/images/sub-categories/game-code-109.webp",
				link: "/slots?p=octoplay",
				alternative_link: "/slots/octoplay",
			},
			{
				name: "Worldmatch",
				slug: "worldmatch",
				category: "slots",
				icon: "/images/sub-categories/game-code-89.webp",
				cover: "/images/sub-categories/game-code-89.webp",
				link: "/slots?p=worldmatch",
				alternative_link: "/slots/worldmatch",
			},
			{
				name: "Mario Club",
				slug: "mario-club",
				category: "slots",
				icon: "/images/sub-categories/game-code-80.webp",
				cover: "/images/sub-categories/game-code-80.webp",
				link: "/slots?p=mario-club",
				alternative_link: "/slots/mario-club",
			},
			{
				name: "Dragoonsoft",
				slug: "dragoonsoft",
				category: "slots",
				icon: "/images/sub-categories/game-code-81.webp",
				cover: "/images/sub-categories/game-code-81.webp",
				link: "/slots?p=dragoonsoft",
				alternative_link: "/slots/dragoonsoft",
			},
			{
				name: "Fun Gaming",
				slug: "fun-gaming",
				category: "slots",
				icon: "/images/sub-categories/game-code-79.webp",
				cover: "/images/sub-categories/game-code-79.webp",
				link: "/slots?p=fun-gaming",
				alternative_link: "/slots/fun-gaming",
			},
			{
				name: "Funky Games",
				slug: "funky-games",
				category: "slots",
				icon: "/images/sub-categories/game-code-35.webp",
				cover: "/images/sub-categories/game-code-35.webp",
				link: "/slots?p=funky-games",
				alternative_link: "/slots/funky-games",
			},
			{
				name: "Live22",
				slug: "live22",
				category: "slots",
				icon: "/images/sub-categories/game-code-45.webp",
				cover: "/images/sub-categories/game-code-45.webp",
				link: "/slots?p=live22",
				alternative_link: "/slots/live22",
			},
			{
				name: "CQ9",
				slug: "cq9",
				category: "slots",
				icon: "/images/sub-categories/game-code-13.webp",
				cover: "/images/sub-categories/game-code-13.webp",
				link: "/slots?p=cq9",
				alternative_link: "/slots/cq9",
			},
			{
				name: "Only Play",
				slug: "only-play",
				category: "slots",
				icon: "/images/sub-categories/game-code-97.webp",
				cover: "/images/sub-categories/game-code-97.webp",
				link: "/slots?p=only-play",
				alternative_link: "/slots/only-play",
			},
			{
				name: "Netent",
				slug: "netent",
				category: "slots",
				icon: "/images/sub-categories/game-code-94.webp",
				cover: "/images/sub-categories/game-code-94.webp",
				link: "/slots?p=netent",
				alternative_link: "/slots/netent",
			},
			{
				name: "Big Time Gaming",
				slug: "big-time-gaming",
				category: "slots",
				icon: "/images/sub-categories/game-code-95.webp",
				cover: "/images/sub-categories/game-code-95.webp",
				link: "/slots?p=big-time-gaming",
				alternative_link: "/slots/big-time-gaming",
			},
			{
				name: "Red Tiger",
				slug: "red-tiger",
				category: "slots",
				icon: "/images/sub-categories/game-code-93.webp",
				cover: "/images/sub-categories/game-code-93.webp",
				link: "/slots?p=red-tiger",
				alternative_link: "/slots/red-tiger",
			},
			{
				name: "Skywind",
				slug: "skywind",
				category: "slots",
				icon: "/images/sub-categories/game-code-90.webp",
				cover: "/images/sub-categories/game-code-90.webp",
				link: "/slots?p=skywind",
				alternative_link: "/slots/skywind",
			},
			{
				name: "Yggdrasil",
				slug: "yggdrasil",
				category: "slots",
				icon: "/images/sub-categories/game-code-42.webp",
				cover: "/images/sub-categories/game-code-42.webp",
				link: "/slots?p=yggdrasil",
				alternative_link: "/slots/yggdrasil",
			},
			{
				name: "Play'n Go",
				slug: "playngo",
				category: "slots",
				icon: "/images/sub-categories/game-code-18.webp",
				cover: "/images/sub-categories/game-code-18.webp",
				link: "/slots?p=playngo",
				alternative_link: "/slots/playngo",
			},
		],
	},
	{
		name: "Live Casino",
		descriptions:
			"Kami dengan bangga menyediakan permainan kasino online langsung terbaik di Asia. Dan bermitra dengan kasino internasional dilengkapi dengan 300 profesional dealer yang profesional dan ramah di berbagai kasino online di seluruh dunia, Anda dapat memilih yang paling nyaman dan pilihlah dealer yang akan memberikan keberuntungan di ujung jari Anda.",
		alias: "Casino Games",
		slug: "casino",
		icon: "/images/categories/casino.svg",
		cover: "/images/categories/casino-cover.webp",
		cover_small: "/images/categories/casino-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "ION Casino",
				slug: "ion-casino",
				category: "casino",
				icon: "/images/sub-categories/game-code-1.webp",
				cover: "/images/categories/casino/game-code-1.webp",
				link: "javascript:openNewTab('/dispatch/game/TRG/Desktop', 'Main')",
				alternative_link: "/casino/ion-casino",
			},
			{
				name: "PP Casino",
				slug: "pp-casino",
				category: "casino",
				icon: "/images/sub-categories/game-code-41.webp",
				cover: "/images/categories/casino/game-code-41.webp",
				link: "/casino?p=pragmatic",
				alternative_link: "/casino/pragmatic",
			},
			{
				name: "MG Live",
				slug: "mg-live",
				category: "casino",
				icon: "/images/sub-categories/game-code-66.webp",
				cover: "/images/categories/casino/game-code-66.webp",
				link: "javascript:openNewTab('/dispatch/game/MGLIVECASINO/Desktop', 'Main')",
				alternative_link: "/casino/mg-live",
			},
			{
				name: "Evo Gaming",
				slug: "evo-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-38.webp",
				cover: "/images/categories/casino/game-code-38.webp",
				link: "/casino?p=evo-gaming",
				alternative_link: "/casino/evo-gaming",
			},
			{
				name: "Ping Pong",
				slug: "ping-pong",
				category: "casino",
				icon: "/images/sub-categories/game-code-105.webp",
				cover: "/images/categories/casino/game-code-105.webp",
				link: "javascript:openNewTab('/dispatch/game/PINGPONG/Desktop', 'Main')",
				alternative_link: "/casino/ping-pong",
			},
			{
				name: "Sexy Baccarat",
				slug: "sexy-baccarat",
				category: "casino",
				icon: "/images/sub-categories/game-code-27.webp",
				cover: "/images/categories/casino/game-code-27.webp",
				link: "javascript:openNewTab('/dispatch/game/SBOSEXYBACCARAT/Desktop', 'Main')",
				alternative_link: "/casino/sexy-baccarat",
			},
			{
				name: "Pretty Gaming",
				slug: "pretty-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-39.webp",
				cover: "/images/categories/casino/game-code-39.webp",
				link: "javascript:openNewTab('/dispatch/game/PRETTYGAMING/Desktop', 'Main')",
				alternative_link: "/casino/pretty-gaming",
			},
			{
				name: "Oriental Gaming",
				slug: "oriental-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-100.webp",
				cover: "/images/categories/casino/game-code-100.webp",
				link: "javascript:openNewTab('/dispatch/game/ORIENTALGAMING/Desktop', 'Main')",
				alternative_link: "/casino/oriental-gaming",
			},
			{
				name: "Asia Gaming",
				slug: "asia-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-14.webp",
				cover: "/images/categories/casino/game-code-14.webp",
				link: "javascript:openNewTab('/dispatch/game/AG/Desktop', 'Main')",
				alternative_link: "/casino/asia-gaming",
			},
			{
				name: "AllBet",
				slug: "allbet",
				category: "casino",
				icon: "/images/sub-categories/game-code-44.webp",
				cover: "/images/categories/casino/game-code-44.webp",
				link: "javascript:openNewTab('/dispatch/game/ALLBET/Desktop', 'Main')",
				alternative_link: "/casino/allbet",
			},
			{
				name: "Opus Live Casino",
				slug: "opus-live-casino",
				category: "casino",
				icon: "/images/sub-categories/game-code-101.webp",
				cover: "/images/categories/casino/game-code-101.webp",
				link: "javascript:openNewTab('/dispatch/game/OPUSLIVECASINO/Desktop', 'Main')",
				alternative_link: "/casino/opus-live-casino",
			},
			{
				name: "SA Gaming",
				slug: "sa-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-84.webp",
				cover: "/images/categories/casino/game-code-84.webp",
				link: "javascript:openNewTab('/dispatch/game/SAGAMING/Desktop', 'Main')",
				alternative_link: "/casino/sa-gaming",
			},
			{
				name: "EBET",
				slug: "ebet",
				category: "casino",
				icon: "/images/sub-categories/game-code-85.webp",
				cover: "/images/categories/casino/game-code-85.webp",
				link: "javascript:openNewTab('/dispatch/game/EBET/Desktop', 'Main')",
				alternative_link: "/casino/ebet",
			},
			{
				name: "Dream Gaming",
				slug: "dream-gaming",
				category: "casino",
				icon: "/images/sub-categories/game-code-43.webp",
				cover: "/images/categories/casino/game-code-43.webp",
				link: "javascript:openNewTab('/dispatch/game/DREAMGAMING/Desktop', 'Main')",
				alternative_link: "/casino/dream-gaming",
			},
			{
				name: "568Win Casino",
				slug: "568win",
				category: "casino",
				icon: "/images/sub-categories/game-code-10.webp",
				cover: "/images/categories/casino/game-code-10.webp",
				link: "javascript:openNewTab('/dispatch/game/SBOCASINO/Desktop', 'Main')",
				alternative_link: "/casino/568win",
			},
		],
	},
	{
		name: "Race",
		descriptions:
			"Masukilah ke jalur cepat bersama kami - di mana adrenalin, aksi-penuh hiburan dan kemenangan bertabrakan! Dari trek berkecepatan tinggi hingga trek yang mendebarkan, saksikan saat mereka melesat menuju garis finis. Pilih pesaing dan pasangkan taruhan Anda, rasakan ketegangannya setiap detik - dan menangkan lombanya!",
		slug: "race",
		alias: "Race Games",
		icon: "/images/categories/race.svg",
		cover: "/images/categories/race-cover.webp",
		cover_small: "/images/categories/race-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "MarbleX",
				slug: "marblex",
				category: "race",
				icon: "/images/sub-categories/game-code-117.webp",
				cover: "/images/categories/race/game-code-117.webp",
				link: "/race?p=marblex",
				alternative_link: "/race/marblex",
			},
		],
	},
	{
		name: "Togel",
		descriptions:
			"Kami berupaya memberikan pelayanan terbaik untuk nomor game 4D dari beberapa vendor",
		slug: "others",
		alias: "Other Games",
		icon: "/images/categories/others.svg",
		cover: "/images/categories/other-cover.webp",
		cover_small: "/images/categories/other-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "Nex4D",
				slug: "nex-4d",
				category: "others",
				icon: "/images/sub-categories/game-code-48.webp",
				cover: "/images/categories/other/game-code-48.webp",
				link: "javascript:openNewTab('/dispatch/game/BALAK4D/Desktop', 'Main')",
				alternative_link: "/others/nex-4d",
			},
		],
	},
	{
		name: "Olahraga",
		descriptions:
			"Nikmati taruhan sports pilihan terbaik dengan tampilan khusus untuk seluruh market Asia, dilengkapi lebih dari 18.500 pertandingan Live dengan Odds terbaik. Kami bermitra resmi dengan provider resmi dari SBOBET dan SABA platform yang menawarkan berbagai macam taruhan olahraga seperti sepakbola, basket, tennis, dll.",
		slug: "sport",
		alias: "Other Games",
		icon: "/images/categories/sports.svg",
		cover: "/images/categories/other-cover.webp",
		cover_small: "/images/categories/other-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "SBO Sportsbook",
				slug: "sbo-sportsbook",
				category: "sport",
				icon: "/images/sub-categories/game-code-5.webp",
				cover: "/images/categories/sport/game-code-5.webp",
				link: "javascript:openNewTab('/dispatch/game/SBO/Desktop', 'Main')",
				alternative_link: "/sport/sbo-sportsbook",
			},
			{
				name: "Saba Sportsbook",
				slug: "saba-sportsbook",
				category: "sport",
				icon: "/images/sub-categories/game-code-23.webp",
				cover: "/images/categories/sport/game-code-23.webp",
				link: "javascript:openNewTab('/dispatch/game/IBCSPORTS/Desktop', 'Main')",
				alternative_link: "/others/saba-sportsbook",
			},
			{
				name: "WBet",
				slug: "wbet",
				category: "sport",
				icon: "/images/sub-categories/game-code-69.webp",
				cover: "/images/categories/sport/game-code-69.webp",
				link: "javascript:openNewTab('/dispatch/game/WBET/Desktop', 'Main')",
				alternative_link: "/others/wbet",
			},
			{
				name: "CMD",
				slug: "cmd",
				category: "sport",
				icon: "/images/sub-categories/game-code-83.webp",
				cover: "/images/categories/sport/game-code-83.webp",
				link: "javascript:openNewTab('/dispatch/game/CMD/Desktop', 'Main')",
				alternative_link: "/others/cmd",
			},
			{
				name: "Opus",
				slug: "opus",
				category: "sport",
				icon: "/images/sub-categories/game-code-71.webp",
				cover: "/images/categories/sport/game-code-71.webp",
				link: "javascript:openNewTab('/dispatch/game/OPUS/Desktop', 'Main')",
				alternative_link: "/others/opus",
			},
			{
				name: "IM Sportsbook",
				slug: "im-sportsbook",
				category: "sport",
				icon: "/images/sub-categories/game-code-86.webp",
				cover: "/images/categories/sport/game-code-86.webp",
				link: "javascript:openNewTab('/dispatch/game/IMSPORTSBOOK/Desktop', 'Main')",
				alternative_link: "/others/im-sportsbook",
			},
			{
				name: "UMbet",
				slug: "umbet",
				category: "sport",
				icon: "/images/sub-categories/game-code-102.webp",
				cover: "/images/categories/sport/game-code-102.webp",
				link: "javascript:openNewTab('/dispatch/game/UMBET/Desktop', 'Main')",
				alternative_link: "/others/umbet",
			},
			{
				name: "Fairbet",
				slug: "fairbet",
				category: "sport",
				icon: "/images/sub-categories/game-code-103.webp",
				cover: "/images/categories/sport/game-code-103.webp",
				link: "javascript:openNewTab('/dispatch/game/FAIRBET/Desktop', 'Main')",
				alternative_link: "/others/fairbet",
			},
			{
				name: "SBO Virtual Sports",
				slug: "sbo-virtual-sports",
				category: "sport",
				icon: "/images/sub-categories/game-code-11.webp",
				cover: "/images/categories/sport/game-code-11.webp",
				link: "javascript:openNewTab('/dispatch/game/SBOVIRTUALGAMES/Desktop', 'Main')",
				alternative_link: "/others/sbo-virtual-sports",
			},
			{
				name: "PP Virtual Sports",
				slug: "pp-virtual-games",
				category: "sport",
				icon: "/images/sub-categories/game-code-55.webp",
				cover: "/images/categories/sport/game-code-55.webp",
				link: "javascript:openNewTab('/dispatch/game/PPVIRTUALGAMES/Desktop', 'Main')",
				alternative_link: "/others/pp-virtual-games",
			},
		],
	},
	{
		name: "Crash Game",
		descriptions:
			"Crash Game adalah permainan yang cukup sederhana - terdiri dari garis yang terus naik dan naik, menggandakan taruhan Anda - hingga akhirnya crash. Selama periode ini, Anda bebas untuk mencairkan kapan pun Anda mau, bahkan secara otomatis. Jika Anda mencairkan sebelum crash secara acak, Anda akan tetap mempertahankan kemenangan Anda - jika tidak, Anda akan kehilangan seluruh taruhan Anda hingga putaran berikutnya.",
		slug: "crash-game",
		alias: "Crash Game",
		icon: "/images/categories/crash-game.svg",
		cover: "/images/categories/cash-game-cover.webp",
		cover_small: "/images/categories/cash-game-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "PP Casino",
				slug: "pragmatic",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-41.webp",
				cover: "/images/categories/sport/game-code-41.webp",
				link: "/crash-game?p=pragmatic",
				alternative_link: "/crash-game?p=pragmatic",
			},
			{
				name: "Aviator",
				slug: "aviator",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-82.webp",
				cover: "/images/categories/sport/game-code-82.webp",
				link: "/crash-game?p=aviator",
				alternative_link: "/crash-game?p=aviator",
			},
			{
				name: "Smartsoft",
				slug: "smartsoft",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-108.webp",
				cover: "/images/categories/sport/game-code-55.webp",
				link: "/crash-game?p=smartsoft",
				alternative_link: "/crash-game/smartsoft",
			},
			{
				name: "MicroGaming",
				slug: "microgaming",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-17.webp",
				cover: "/images/categories/sport/game-code-55.webp",
				link: "/crash-game?p=microgaming",
				alternative_link: "/crash-game/microgaming",
			},
			{
				name: "Spinix",
				slug: "spinix",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-91.webp",
				cover: "/images/categories/sport/game-code-55.webp",
				link: "/crash-game?p=spinix",
				alternative_link: "/crash-game/spinix",
			},
			{
				name: "Gemini",
				slug: "gemini",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-107.webp",
				cover: "/images/categories/sport/game-code-107.webp",
				link: "/crash-game?p=gemini",
				alternative_link: "/crash-game/gemini",
			},
			{
				name: "AdvantPlay Mini Game",
				slug: "advantplay-mini-game",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-62.webp",
				cover: "/images/categories/sport/game-code-62.webp",
				link: "/crash-game?p=advantplay-mini-game",
				alternative_link: "/crash-game/advantplay-mini-game",
			},
			{
				name: "Spade Gaming",
				slug: "spade-gaming",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-29.webp",
				cover: "/images/categories/sport/game-code-29.webp",
				link: "/crash-game?p=spade-gaming",
				alternative_link: "/crash-game/spade-gaming",
			},
			{
				name: "Only Play",
				slug: "only-play",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-97.webp",
				cover: "/images/categories/sport/game-code-97.webp",
				link: "/crash-game?p=only-play",
				alternative_link: "/crash-game/only-play",
			},
			{
				name: "Joker",
				slug: "joker",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-6.webp",
				cover: "/images/categories/sport/game-code-6.webp",
				link: "/crash-game?p=joker",
				alternative_link: "/crash-game/joker",
			},
			{
				name: "Dragoonsoft",
				slug: "dragoonsoft",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-81.webp",
				cover: "/images/categories/sport/game-code-81.webp",
				link: "/crash-game?p=dragoonsoft",
				alternative_link: "/crash-game/dragoonsoft",
			},
			{
				name: "Funky Games",
				slug: "funky-games",
				category: "crash-game",
				icon: "/images/sub-categories/game-code-35.webp",
				cover: "/images/categories/sport/game-code-35.webp",
				link: "/crash-game?p=funky-games",
				alternative_link: "/crash-game/funky-games",
			},
		],
	},
	{
		name: "Arcade",
		descriptions:
			"Kami hadirkan game menarik dengan taruhan uang asli dari permainan tembak ikan, capit duit, MM tangkas bagi para penggemar tangkas. Semua lengkap kami hadirkan untuk anda.",
		slug: "arcade",
		alias: "Arcade Game",
		icon: "/images/categories/arcade.svg",
		cover: "/images/categories/arcade-cover.webp",
		cover_small: "/images/categories/arcade-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "Pragmatic Play",
				slug: "pragmatic",
				category: "arcade",
				icon: "/images/sub-categories/game-code-118.webp",
				cover: "/images/categories/arcade/game-code-118.webp",
				link: "/arcade?p=pragmatic",
				alternative_link: "/arcade/pragmatic",
			},
			{
				name: "MicroGaming",
				slug: "microgaming",
				category: "arcade",
				icon: "/images/sub-categories/game-code-119.webp",
				cover: "/images/categories/arcade/game-code-119.webp",
				link: "/arcade?p=microgaming",
				alternative_link: "/arcade/microgaming",
			},
			{
				name: "Hacksaw",
				slug: "hacksaw",
				category: "arcade",
				icon: "/images/sub-categories/game-code-120.webp",
				cover: "/images/categories/arcade/game-code-120.webp",
				link: "/arcade?p=hacksaw",
				alternative_link: "/arcade/hacksaw",
			},
			{
				name: "King Midas",
				slug: "king-midas",
				category: "arcade",
				icon: "/images/sub-categories/game-code-121.webp",
				cover: "/images/categories/arcade/game-code-121.webp",
				link: "/arcade?p=king-midas",
				alternative_link: "/arcade/king-midas",
			},
			{
				name: "JILI",
				slug: "jili",
				category: "arcade",
				icon: "/images/sub-categories/game-code-122.webp",
				cover: "/images/categories/arcade/game-code-122.webp",
				link: "/arcade?p=jili",
				alternative_link: "/arcade/jili",
			},
			{
				name: "Gemini",
				slug: "gemini",
				category: "arcade",
				icon: "/images/sub-categories/game-code-123.webp",
				cover: "/images/categories/arcade/game-code-123.webp",
				link: "/arcade?p=gemini",
				alternative_link: "/arcade/gemini",
			},
			{
				name: "Aviator",
				slug: "aviator",
				category: "arcade",
				icon: "/images/sub-categories/game-code-124.webp",
				cover: "/images/categories/arcade/game-code-124.webp",
				link: "/arcade?p=aviator",
				alternative_link: "/arcade/aviator",
			},
			{
				name: "Fachai",
				slug: "fachai",
				category: "arcade",
				icon: "/images/sub-categories/game-code-125.webp",
				cover: "/images/categories/arcade/game-code-125.webp",
				link: "/arcade?p=fachai",
				alternative_link: "/arcade/fachai",
			},
			{
				name: "Joker",
				slug: "joker",
				category: "arcade",
				icon: "/images/sub-categories/game-code-126.webp",
				cover: "/images/categories/arcade/game-code-126.webp",
				link: "/arcade?p=joker",
				alternative_link: "/arcade/joker",
			},
			{
				name: "AMB Slot",
				slug: "amb-slot",
				category: "arcade",
				icon: "/images/sub-categories/game-code-127.webp",
				cover: "/images/categories/arcade/game-code-127.webp",
				link: "/arcade?p=amb-slot",
				alternative_link: "/arcade/amb-slot",
			},
			{
				name: "Spinix",
				slug: "spinix",
				category: "arcade",
				icon: "/images/sub-categories/game-code-128.webp",
				cover: "/images/categories/arcade/game-code-128.webp",
				link: "/arcade?p=spinix",
				alternative_link: "/arcade/spinix",
			},
			{
				name: "Crowd Play",
				slug: "crowd-play",
				category: "arcade",
				icon: "/images/sub-categories/game-code-129.webp",
				cover: "/images/categories/arcade/game-code-129.webp",
				link: "/arcade?p=crowd-play",
				alternative_link: "/arcade/crowd-play",
			},
			{
				name: "VPower",
				slug: "vpower",
				category: "arcade",
				icon: "/images/sub-categories/game-code-130.webp",
				cover: "/images/categories/arcade/game-code-130.webp",
				link: "/arcade?p=vpower",
				alternative_link: "/arcade/vpower",
			},
			{
				name: "Worldmatch",
				slug: "worldmatch",
				category: "arcade",
				icon: "/images/sub-categories/game-code-131.webp",
				cover: "/images/categories/arcade/game-code-131.webp",
				link: "/arcade?p=worldmatch",
				alternative_link: "/arcade/worldmatch",
			},
			{
				name: "Mario Club",
				slug: "mario-club",
				category: "arcade",
				icon: "/images/sub-categories/game-code-132.webp",
				cover: "/images/categories/arcade/game-code-132.webp",
				link: "/arcade?p=mario-club",
				alternative_link: "/arcade/mario-club",
			},
			{
				name: "Dragoonsoft",
				slug: "dragoonsoft",
				category: "arcade",
				icon: "/images/sub-categories/game-code-133.webp",
				cover: "/images/categories/arcade/game-code-133.webp",
				link: "/arcade?p=dragoonsoft",
				alternative_link: "/arcade/dragoonsoft",
			},
			{
				name: "CQ9",
				slug: "cq9",
				category: "arcade",
				icon: "/images/sub-categories/game-code-134.webp",
				cover: "/images/categories/arcade/game-code-134.webp",
				link: "/arcade?p=cq9",
				alternative_link: "/arcade/cq9",
			},
			{
				name: "Fun Gaming",
				slug: "fun-gaming",
				category: "arcade",
				icon: "/images/sub-categories/game-code-135.webp",
				cover: "/images/categories/arcade/game-code-135.webp",
				link: "/arcade?p=fun-gaming",
				alternative_link: "/arcade/fun-gaming",
			},
			{
				name: "MM Tangkas",
				slug: "jili",
				category: "arcade",
				icon: "/images/sub-categories/game-code-136.webp",
				cover: "/images/categories/arcade/game-code-136.webp",
				link: "/arcade?p=jili",
				alternative_link: "/arcade/jili",
			},
			{
				name: "Skywind",
				slug: "skywind",
				category: "arcade",
				icon: "/images/sub-categories/game-code-137.webp",
				cover: "/images/categories/arcade/game-code-137.webp",
				link: "/arcade?p=skywind",
				alternative_link: "/arcade/skywind",
			},
			{
				name: "JDB",
				slug: "jdb",
				category: "arcade",
				icon: "/images/sub-categories/game-code-138.webp",
				cover: "/images/categories/arcade/game-code-138.webp",
				link: "/arcade?p=jdb",
				alternative_link: "/arcade/jdb",
			},
			{
				name: "Funky Games",
				slug: "funky-games",
				category: "arcade",
				icon: "/images/sub-categories/game-code-139.webp",
				cover: "/images/categories/arcade/game-code-139.webp",
				link: "/arcade?p=funky-games",
				alternative_link: "/arcade/funky-games",
			},
		],
	},
	{
		name: "Poker",
		descriptions:
			"Dengan bangga kami persembahkan BALAKPLAY dan 9GAMING sebagai provider pilihan terbaik Se Asia untuk jenis permainan poker dan domino. di dalamnya dilengkapi dengan berbagai permainan seperti poker, dominoQQ, poker omaha, bandar poker, bandar ceme, capsa susun.",
		slug: "poker",
		alias: "Poker Games",
		icon: "/images/categories/poker.svg",
		cover: "/images/categories/poker-cover.webp",
		cover_small: "/images/categories/poker-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "Balak Play",
				slug: "balak-play",
				category: "poker",
				icon: "/images/sub-categories/game-code-24.webp",
				cover: "/images/categories/poker/game-code-24.webp",
				link: "javascript:openNewTab('/dispatch/game/G8POKER/Desktop', 'Main')",
				alternative_link: "/poker/balak-play",
			},
			{
				name: "9Gaming",
				slug: "9gaming",
				category: "poker",
				icon: "/images/sub-categories/game-code-32.webp",
				cover: "/images/categories/poker/game-code-32.webp",
				link: "javascript:openNewTab('/dispatch/game/ONEPOKER/Desktop', 'Main')",
				alternative_link: "/poker/9gaming",
			},
		],
	},
	{
		name: "E-Sports",
		descriptions:
			"Nikmati taruhan sports pilihan terbaik dengan tampilan khusus untuk seluruh market Asia, dilengkapi lebih dari 18.500 pertandingan Live dengan Odds terbaik. Kami bermitra resmi dengan provider resmi dari SBOBET dan SABA platform yang menawarkan berbagai macam taruhan olahraga seperti sepakbola, basket, tennis, dll.",
		slug: "e-sports",
		alias: "E-Sports Games",
		icon: "/images/categories/e-sports.svg",
		cover: "/images/categories/e-sports-cover.webp",
		cover_small: "/images/categories/e-sports-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "TF Gaming",
				slug: "tf-gaming",
				category: "e-sports",
				icon: "/images/sub-categories/game-code-58.webp",
				cover: "/images/categories/e-sport/game-code-58.webp",
				link: "javascript:openNewTab('/dispatch/game/TFGAMING/Desktop', 'Main')",
				alternative_link: "/e-sports/tf-gaming",
			},
		],
	},
	{
		name: "Sabung Ayam",
		descriptions:
			"Permainan Sabung Ayam adalah permainan klasik. Berkat kemajuan teknologi, permainan klasik ini dapat dibeli secara online dan dapat dimainkan dengan taruhan online pada pertandingan sabung ayam kapan pun dan di mana pun.",
		slug: "cockfight",
		alias: "Permainan Sabung Ayam",
		icon: "/images/categories/cockfight.svg",
		cover: "/images/categories/cockfight-cover.webp",
		cover_small: "/images/categories/cockfight-cover-small.webp",
		style: {
			bg_gradient: "hero-background-dark",
			glow_effect_1: "glow-effect-dark",
			glow_effect_2: "glow-effect-dark-2",
			her0_image: "hero-image-dark",
		},
		sub: [
			{
				name: "GA28",
				slug: "ga28",
				category: "cockfight",
				icon: "/images/sub-categories/game-code-111.webp",
				cover: "/images/categories/cockfight/game-code-111.webp",
				link: "javascript:openNewTab('/dispatch/game/GA28/Desktop', 'Main')",
				alternative_link: "/cockfight/ga28",
			},
			{
				name: "SV388",
				slug: "sv388",
				category: "cockfight",
				icon: "/images/sub-categories/game-code-57.webp",
				cover: "/images/categories/cockfight/game-code-57.webp",
				link: "javascript:openNewTab('/dispatch/game/SV388/Desktop', 'Main')",
				alternative_link: "/cockfight/sv388",
			},
			{
				name: "WS168",
				slug: "ws168",
				category: "cockfight",
				icon: "/images/sub-categories/game-code-104.webp",
				cover: "/images/categories/cockfight/game-code-104.webp",
				link: "javascript:openNewTab('/dispatch/game/WS168/Desktop', 'Main')",
				alternative_link: "/cockfight/ws168",
			},
		],
	},
	{
		name: "Promosi",
		slug: "promotion",
		icon: "/images/categories/promotion.webp",
	},
];
export const SlotsProvidersCategory: Partner[] = [
	{
		name: "Pragmatic Play",
		logo: "/images/partners/game-code-7.webp",
		logo_colored: "/images/partners/game-code-7-colored.webp",
		category: "slots",
		slug: "pragmatic",
		url: "/slots?p=pragmatic",
	},
	{
		name: "PG Soft",
		logo: "/images/partners/game-code-9.webp",
		logo_colored: "/images/partners/game-code-9-colored.webp",
		category: "slots",
		slug: "pgsoft",
		url: "/slots?p=pgsoft",
	},
	{
		name: "Slot88",
		logo: "/images/partners/game-code-40.webp",
		logo_colored: "/images/partners/game-code-40-colored.webp",
		category: "slots",
		slug: "slot88",
		url: "/slots?p=slot88",
	},
	{
		name: "Hacksaw Gaming",
		logo: "/images/partners/game-code-98.webp",
		logo_colored: "/images/partners/game-code-98-colored.webp",
		category: "slots",
		slug: "hacksaw",
		url: "/slots?p=hacksaw",
	},
	{
		name: "Fat Panda",
		logo: "/images/partners/game-code-112.webp",
		logo_colored: "/images/partners/game-code-112-colored.webp",
		category: "slots",
		slug: "fat-panda",
		url: "/slots?p=fat-panda",
	},
	{
		name: "Nolimit City",
		logo: "/images/partners/game-code-92.webp",
		logo_colored: "/images/partners/game-code-92-colored.webp",
		category: "slots",
		slug: "no-limit-city",
		url: "/slots?p=no-limit-city",
	},
	{
		name: "JILI",
		logo: "/images/partners/game-code-70.webp",
		logo_colored: "/images/partners/game-code-70-colored.webp",
		category: "slots",
		slug: "jili",
		url: "/slots?p=jili",
	},
	{
		name: "Habanero",
		logo: "/images/partners/game-code-16.webp",
		logo_colored: "/images/partners/game-code-16-colored.webp",
		category: "slots",
		slug: "habanero",
		url: "/slots?p=habanero",
	},
	{
		name: "Microgaming",
		logo: "/images/partners/game-code-17.webp",
		logo_colored: "/images/partners/game-code-72-colored.webp",
		category: "slots",
		slug: "microgaming",
		url: "/slots?p=microgaming",
	},
	{
		name: "5G Games",
		url: "/slots?p=fivegg",
		logo: "/images/partners/game-code-114.webp",
		logo_colored: "/images/partners/game-code-114-colored.webp",
		category: "slots",
		slug: "fivegg",
	},
	{
		name: "Playtech",
		url: "/slots?p=playtech",
		logo: "/images/partners/game-code-2.webp",
		logo_colored: "/images/partners/game-code-2-colored.webp",
		category: "slots",
		slug: "playtech",
	},
	{
		name: "Spade Gaming",
		url: "/slots?p=spade-gaming",
		logo: "/images/partners/game-code-29.webp",
		logo_colored: "/images/partners/game-code-29-colored.webp",
		category: "slots",
		slug: "spade-gaming",
	},
	{
		name: "King Midas",
		url: "/slots?p=king-midas",
		logo: "/images/partners/game-code-116.webp",
		logo_colored: "/images/partners/game-code-116-colored.webp",
		category: "slots",
		slug: "king-midas",
	},
	{
		name: "Fast Spin",
		url: "/slots?p=fast-spin",
		logo: "/images/partners/game-code-110.webp",
		logo_colored: "/images/partners/game-code-110-colored.webp",
		category: "slots",
		slug: "fast-spin",
	},
	{
		name: "V Plus",
		url: "/slots?vplus",
		logo: "/images/partners/game-code-115.webp",
		logo_colored: "/images/partners/game-code-115-colored.webp",
		category: "slots",
		slug: "vplus",
	},
	{
		name: "Joker",
		url: "/slots?p=joker",
		logo: "/images/partners/game-code-6.webp",
		logo_colored: "/images/partners/game-code-6-colored.webp",
		category: "slots",
		slug: "joker",
	},
	{
		name: "FA Chai",
		url: "/slots?p=fachai",
		logo: "/images/partners/game-code-72.webp",
		logo_colored: "/images/partners/game-code-72-colored.webp",
		category: "slots",
		slug: "fachai",
	},
	{
		name: "Advant Play",
		url: "/slots?p=advantplay",
		logo: "/images/partners/game-code-54.webp",
		logo_colored: "/images/partners/game-code-54-colored.webp",
		category: "slots",
		slug: "advantplay",
	},
	{
		name: "Smartsoft Gaming",
		url: "/slots?p=smartsoft",
		logo: "/images/partners/game-code-108.webp",
		logo_colored: "/images/partners/game-code-108-colored.webp",
		category: "slots",
		slug: "smartsoft",
	},
	{
		name: "Naga Games",
		url: "/slots?p=naga-games",
		logo: "/images/partners/game-code-87.webp",
		logo_colored: "/images/partners/game-code-87-colored.webp",
		category: "slots",
		slug: "naga-games",
	},
	{
		name: "JDB",
		url: "/slots?p=jdb",
		logo: "/images/partners/game-code-51.webp",
		logo_colored: "/images/partners/game-code-51-colored.webp",
		category: "slots",
		slug: "jdb",
	},
	{
		name: "Play Star",
		url: "/slots?p=playstar",
		logo: "/images/partners/game-code-65.webp",
		logo_colored: "/images/partners/game-code-65-colored.webp",
		category: "slots",
		slug: "playstar",
	},
	{
		name: "SpinX",
		url: "/slots?p=spinix",
		logo: "/images/partners/game-code-91.webp",
		logo_colored: "/images/partners/game-code-91-colored.webp",
		category: "slots",
		slug: "spinix",
	},
	{
		name: "Crowd Play",
		url: "/slots?p=crowd-play",
		logo: "/images/partners/game-code-73.webp",
		logo_colored: "/images/partners/game-code-73-colored.webp",
		category: "slots",
		slug: "crowd-play",
	},
	{
		name: "Ion Slot",
		url: "/slots?p=ion-slot",
		logo: "/images/partners/game-code-50.webp",
		logo_colored: "/images/partners/game-code-50-colored.webp",
		category: "slots",
		slug: "ion-slot",
	},
	{
		name: "Bigpot Gaming",
		url: "/slots?p=bigpot",
		logo: "/images/partners/game-code-75.webp",
		logo_colored: "/images/partners/game-code-75-colored.webp",
		category: "slots",
		slug: "bigpot",
	},
	{
		name: "KA Gaming",
		url: "/slots?vpower",
		logo: "/images/partners/game-code-77.webp",
		logo_colored: "/images/partners/game-code-77-colored.webp",
		category: "slots",
		slug: "vpower",
	},
	{
		name: "Askmebet",
		url: "/slots?p=amb-slot",
		logo: "/images/partners/game-code-61.webp",
		logo_colored: "/images/partners/game-code-61-colored.webp",
		category: "slots",
		slug: "amb-slot",
	},
	{
		name: "WorldMatch",
		url: "/slots?p=worldmatch",
		logo: "/images/partners/game-code-89.webp",
		logo_colored: "/images/partners/game-code-89-colored.webp",
		category: "slots",
		slug: "worldmatch",
	},
	{
		name: "Octoplay",
		url: "/slots?p=octoplay",
		logo: "/images/partners/game-code-109.webp",
		logo_colored: "/images/partners/game-code-109-colored.webp",
		category: "slots",
		slug: "octoplay",
	},
	{
		name: "Mario Club",
		url: "/slots?p=mario-club",
		logo: "/images/partners/game-code-80.webp",
		logo_colored: "/images/partners/game-code-80-colored.webp",
		category: "slots",
		slug: "mario-club",
	},
	{
		name: "Dragoon Soft",
		url: "/slots?p=dragoonsoft",
		logo: "/images/partners/game-code-81.webp",
		logo_colored: "/images/partners/game-code-81-colored.webp",
		category: "slots",
		slug: "dragoonsoft",
	},
	{
		name: "FG Games",
		url: "/slots?p=fun-gaming",
		logo: "/images/partners/game-code-79.webp",
		logo_colored: "/images/partners/game-code-79-colored.webp",
		category: "slots",
		slug: "fun-gaming",
	},
	{
		name: "Funky Games",
		url: "/slots?p=funky-games",
		logo: "/images/partners/game-code-35.webp",
		logo_colored: "/images/partners/game-code-35-colored.webp",
		category: "slots",
		slug: "funky-games",
	},
	{
		name: "Live22",
		url: "/slots?p=live22",
		logo: "/images/partners/game-code-45.webp",
		logo_colored: "/images/partners/game-code-45-colored.webp",
		category: "slots",
		slug: "live22",
	},
	{
		name: "CQ9",
		url: "/slots?p=cq9",
		logo: "/images/partners/game-code-13.webp",
		logo_colored: "/images/partners/game-code-13-colored.webp",
		category: "slots",
		slug: "cq9",
	},
	{
		name: "Onlyplay",
		url: "/slots?p=only-play",
		logo: "/images/partners/game-code-97.webp",
		logo_colored: "/images/partners/game-code-97-colored.webp",
		category: "slots",
		slug: "only-play",
	},
	{
		name: "NetEnt",
		url: "/slots?p=netent",
		logo: "/images/partners/game-code-94.webp",
		logo_colored: "/images/partners/game-code-94-colored.webp",
		category: "slots",
		slug: "netent",
	},
	{
		name: "BigTime Gaming",
		url: "/slots?p=big-time-gaming",
		logo: "/images/partners/game-code-95.webp",
		logo_colored: "/images/partners/game-code-95-colored.webp",
		category: "slots",
		slug: "big-time-gaming",
	},
	{
		name: "Red Tiger",
		url: "/slots?p=red-tiger",
		logo: "/images/partners/game-code-93.webp",
		logo_colored: "/images/partners/game-code-93-colored.webp",
		category: "slots",
		slug: "red-tiger",
	},
	{
		name: "Skywind Group",
		url: "/slots?p=skywind",
		logo: "/images/partners/game-code-90.webp",
		logo_colored: "/images/partners/game-code-90-colored.webp",
		category: "slots",
		slug: "skywind",
	},
	{
		name: "Yggdrasil",
		url: "/slots?p=yggdrasil",
		logo: "/images/partners/game-code-42.webp",
		logo_colored: "/images/partners/game-code-42-colored.webp",
		category: "slots",
		slug: "yggdrasil",
	},
	{
		name: "Play'n GO",
		url: "/slots?p=playngo",
		logo: "/images/partners/game-code-18.webp",
		logo_colored: "/images/partners/game-code-18-colored.webp",
		category: "slots",
		slug: "playngo",
	},
];
export const CrashProvidersCategory: Partner[] = [
	{
		name: "PP Casino",
		logo: "/images/categories/crash-game/game-code-41.webp",
		logo_colored: "/images/categories/crash-game/game-code-41.webp",
		category: "crash-game",
		slug: "pplivecasino",
		url: "/crash-game?p=pplivecasino",
	},
	{
		name: "Aviator",
		logo: "/images/categories/crash-game/game-code-82.webp",
		logo_colored: "/images/categories/crash-game/game-code-82.webp",
		category: "crash-game",
		slug: "spribe",
		url: "/crash-game?p=spribe",
	},
	{
		name: "Microgaming",
		logo: "/images/categories/crash-game/game-code-17.webp",
		logo_colored: "/images/categories/crash-game/game-code-17.webp",
		category: "crash-game",
		slug: "microgaming",
		url: "/crash-game?p=microgaming",
	},
	{
		name: "Smartsoft",
		logo: "/images/categories/crash-game/game-code-108.webp",
		logo_colored: "/images/categories/crash-game/game-code-108.webp",
		category: "crash-game",
		slug: "smartsoft",
		url: "/crash-game?p=smartsoft",
	},
	{
		name: "Spinix",
		logo: "/images/categories/crash-game/game-code-91.webp",
		logo_colored: "/images/categories/crash-game/game-code-91.webp",
		category: "crash-game",
		slug: "spinix",
		url: "/crash-game?p=spinix",
	},
	{
		name: "Gemini",
		logo: "/images/categories/crash-game/game-code-107.webp",
		logo_colored: "/images/categories/crash-game/game-code-107.webp",
		category: "crash-game",
		slug: "gemini",
		url: "/crash-game?p=gemini",
	},
	{
		name: "AdvantPlay Mini Game",
		logo: "/images/categories/crash-game/game-code-62.webp",
		logo_colored: "/images/categories/crash-game/game-code-62.webp",
		category: "crash-game",
		slug: "advantplay-mini-game",
		url: "/crash-game?p=advantplay-mini-game",
	},
	{
		name: "Spade Gaming",
		logo: "/images/categories/crash-game/game-code-29.webp",
		logo_colored: "/images/categories/crash-game/game-code-29.webp",
		category: "crash-game",
		slug: "spade-gaming",
		url: "/crash-game?p=spade-gaming",
	},
	{
		name: "Only Play",
		logo: "/images/categories/crash-game/game-code-97.webp",
		logo_colored: "/images/categories/crash-game/game-code-97.webp",
		category: "crash-game",
		slug: "only-play",
		url: "/crash-game?p=only-play",
	},
	{
		name: "Joker",
		logo: "/images/categories/crash-game/game-code-6.webp",
		logo_colored: "/images/categories/crash-game/game-code-6.webp",
		category: "crash-game",
		slug: "joker",
		url: "/crash-game?p=joker",
	},
	{
		name: "Dragoonsoft",
		logo: "/images/categories/crash-game/game-code-81.webp",
		logo_colored: "/images/categories/crash-game/game-code-81.webp",
		category: "crash-game",
		slug: "dragoonsoft",
		url: "/crash-game?p=dragoonsoft",
	},
	{
		name: "Funky Games",
		logo: "/images/categories/crash-game/game-code-35.webp",
		logo_colored: "/images/categories/crash-game/game-code-35.webp",
		category: "crash-game",
		slug: "sbo-funky-game",
		url: "/crash-game?p=sbo-funky-game",
	},
];
export const ArcadeProvidersCategory: Partner[] = [
	{
		name: "Pragmatic Play",
		logo: "/images/categories/arcade/game-code-7.webp",
		logo_colored: "/images/categories/arcade/game-code-7.webp",
		category: "arcade",
		slug: "pragmatic",
		url: "/arcade?p=pragmatic",
	},
	{
		name: "MicroGaming",
		logo: "/images/categories/arcade/game-code-17.webp",
		logo_colored: "/images/categories/arcade/game-code-17.webp",
		category: "arcade",
		slug: "microGaming",
		url: "/arcade?p=microGaming",
	},
	{
		name: "Hacksaw",
		logo: "/images/categories/arcade/game-code-98.webp",
		logo_colored: "/images/categories/arcade/game-code-98.webp",
		category: "arcade",
		slug: "hacksaw",
		url: "/arcade?p=hacksaw",
	},
	{
		name: "King Midas",
		logo: "/images/categories/arcade/game-code-116.webp",
		logo_colored: "/images/categories/arcade/game-code-116.webp",
		category: "arcade",
		slug: "king-midas",
		url: "/arcade?p=king-midas",
	},
	{
		name: "Jili",
		logo: "/images/categories/arcade/game-code-70.webp",
		logo_colored: "/images/categories/arcade/game-code-70.webp",
		category: "arcade",
		slug: "jili",
		url: "/arcade?p=jili",
	},
	{
		name: "Gemini",
		logo: "/images/categories/arcade/game-code-107.webp",
		logo_colored: "/images/categories/arcade/game-code-107.webp",
		category: "arcade",
		slug: "gemini",
		url: "/arcade?p=gemini",
	},
	{
		name: "Aviator",
		logo: "/images/categories/arcade/game-code-82.webp",
		logo_colored: "/images/categories/arcade/game-code-82.webp",
		category: "arcade",
		slug: "aviator",
		url: "/arcade?p=aviator",
	},
	{
		name: "Fachai",
		logo: "/images/categories/arcade/game-code-72.webp",
		logo_colored: "/images/categories/arcade/game-code-72.webp",
		category: "arcade",
		slug: "fachai",
		url: "/arcade?p=fachai",
	},
	{
		name: "Joker",
		logo: "/images/categories/arcade/game-code-6.webp",
		logo_colored: "/images/categories/arcade/game-code-6.webp",
		category: "arcade",
		slug: "joker",
		url: "/arcade?p=joker",
	},
	{
		name: "Spinix",
		logo: "/images/categories/arcade/game-code-91.webp",
		logo_colored: "/images/categories/arcade/game-code-91.webp",
		category: "arcade",
		slug: "spinix",
		url: "/arcade?p=spinix",
	},
	{
		name: "AMB Slot",
		logo: "/images/categories/arcade/game-code-61.webp",
		logo_colored: "/images/categories/arcade/game-code-61.webp",
		category: "arcade",
		slug: "amb-slot",
		url: "/arcade?p=amb-slot",
	},
	{
		name: "Crowd Play",
		logo: "/images/categories/arcade/game-code-73.webp",
		logo_colored: "/images/categories/arcade/game-code-73.webp",
		category: "arcade",
		slug: "crowd-play",
		url: "/arcade?p=crowd-play",
	},
	{
		name: "VPower",
		logo: "/images/categories/arcade/game-code-77.webp",
		logo_colored: "/images/categories/arcade/game-code-77.webp",
		category: "arcade",
		slug: "vpower",
		url: "/arcade?p=vpower",
	},
	{
		name: "Worldmatch",
		logo: "/images/categories/arcade/game-code-89.webp",
		logo_colored: "/images/categories/arcade/game-code-89.webp",
		category: "arcade",
		slug: "worldmatch",
		url: "/arcade?p=worldmatch",
	},
	{
		name: "Mario Club",
		logo: "/images/categories/arcade/game-code-80.webp",
		logo_colored: "/images/categories/arcade/game-code-80.webp",
		category: "arcade",
		slug: "mario-club",
		url: "/arcade?p=mario-club",
	},
	{
		name: "Dragoonsoft",
		logo: "/images/categories/arcade/game-code-81.webp",
		logo_colored: "/images/categories/arcade/game-code-81.webp",
		category: "arcade",
		slug: "dragoonsoft",
		url: "/arcade?p=dragoonsoft",
	},
	{
		name: "CQ9",
		logo: "/images/categories/arcade/game-code-13.webp",
		logo_colored: "/images/categories/arcade/game-code-13.webp",
		category: "arcade",
		slug: "cq9",
		url: "/arcade?p=cq9",
	},
	{
		name: "Fun Gaming",
		logo: "/images/categories/arcade/game-code-79.webp",
		logo_colored: "/images/categories/arcade/game-code-79.webp",
		category: "arcade",
		slug: "fun-gaming",
		url: "/arcade?p=fun-gaming",
	},
	{
		name: "MM Tangkas",
		logo: "/images/categories/arcade/game-code-96.webp",
		logo_colored: "/images/categories/arcade/game-code-96.webp",
		category: "arcade",
		slug: "g8-tangkas",
		url: "/arcade?p=g8-tangkas",
	},
	{
		name: "Skywind",
		logo: "/images/categories/arcade/game-code-90.webp",
		logo_colored: "/images/categories/arcade/game-code-90.webp",
		category: "arcade",
		slug: "skywind",
		url: "/arcade?p=skywind",
	},
	{
		name: "JDB",
		logo: "/images/categories/arcade/game-code-51.webp",
		logo_colored: "/images/categories/arcade/game-code-51.webp",
		category: "arcade",
		slug: "jdb",
		url: "/arcade?p=jdb",
	},
	{
		name: "Funky Games",
		logo: "/images/categories/arcade/game-code-35.webp",
		logo_colored: "/images/categories/arcade/game-code-35.webp",
		category: "arcade",
		slug: "funky-games",
		url: "/arcade?p=funky-games",
	},
];
export const MarblexProvidersCategory: Partner[] = [
	{
		name: "Marblex",
		logo: "/images/sub-categories/game-code-117.webp",
		logo_colored: "/images/sub-categories/game-code-117.webp",
		category: "race",
		slug: "marblex",
		url: "/race?p=marblex",
	},
];
