export const PPCasinoGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 41,
		name: "Spaceman",
		gameCode: "PPLiveCasino_1301",
		gameImage: "PPLiveCasino_1301.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PPLIVECASINO/Desktop/PPLiveCasino_1301', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 41,
		name: "Big Bass Crash",
		gameCode: "PPLiveCasino_1320",
		gameImage: "PPLiveCasino_1320.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PPLIVECASINO/Desktop/PPLiveCasino_1320', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 41,
		name: "Slot88 High Flyer",
		gameCode: "PPLiveCasino_2201",
		gameImage: "PPLiveCasino_2201.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PPLIVECASINO/Desktop/PPLiveCasino_2201', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const AviatorGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 82,
		name: "Aviator",
		gameCode: "imgame12001",
		gameImage: "imgame12001.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SPRIBE/Desktop/imgame12001', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashSmartsoft: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "DoubleX",
		gameCode: "XGames_SlicerX",
		gameImage: "XGames_SlicerX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_SlicerX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "HelicopterX",
		gameCode: "XGames_HelicopterX",
		gameImage: "XGames_HelicopterX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_HelicopterX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "RollX",
		gameCode: "Games_RollX",
		gameImage: "Games_RollX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/Games_RollX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "CricketX",
		gameCode: "XGames_CricketX",
		gameImage: "XGames_CricketX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_CricketX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "JetX3",
		gameCode: "XGames_JetX3",
		gameImage: "XGames_JetX3.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_JetX3', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "RodeoX",
		gameCode: "XGames_RodeoX",
		gameImage: "XGames_RodeoX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_RodeoX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "MineIsland",
		gameCode: "Games_MineIsland",
		gameImage: "Games_MineIsland.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/Games_MineIsland', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "4 Bonuses Bonanza",
		gameCode: "Games_PlinkoJoker",
		gameImage: "Games_PlinkoJoker.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/Games_PlinkoJoker', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "CricketerX",
		gameCode: "XGames_CricketerX",
		gameImage: "XGames_CricketerX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_CricketerX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "JetX",
		gameCode: "JetX_JetX",
		gameImage: "JetX_JetX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/JetX_JetX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "Smash X",
		gameCode: "Games_SmashX",
		gameImage: "Games_SmashX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/Games_SmashX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "Balloon",
		gameCode: "Games_Balloon",
		gameImage: "Games_Balloon.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/Games_Balloon', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "TowerX",
		gameCode: "XGames_TowerX",
		gameImage: "XGames_TowerX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_TowerX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 108,
		name: "Crash Duel X",
		gameCode: "XGames_TugOfWar",
		gameImage: "XGames_TugOfWar.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SMARTSOFT/Desktop/XGames_TugOfWar', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashMicroGaming: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 17,
		name: "Incredible Balloon Machine",
		gameCode: "SMG_theIncredibleBalloonMachine",
		gameImage: "SMG_theIncredibleBalloonMachine.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MICROGAMING/Desktop/SMG_theIncredibleBalloonMachine', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 17,
		name: "FlyX",
		gameCode: "SMG_flyX",
		gameImage: "SMG_flyX.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MICROGAMING/Desktop/SMG_flyX', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashSpinixGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 91,
		name: "Greedy Gold",
		gameCode: "_620a1cb956761475ac7a0ea9",
		gameImage: "_620a1cb956761475ac7a0ea9.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SPINIX/Desktop/_620a1cb956761475ac7a0ea9', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 91,
		name: "Greedy Mine",
		gameCode: "_6063f16516df452cdc2d604d",
		gameImage: "_6063f16516df452cdc2d604d.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SPINIX/Desktop/_6063f16516df452cdc2d604d', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const GeminiGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Crash Meteor",
		gameCode: "MultiPlayerCrash",
		gameImage: "MultiPlayerCrash.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerCrash', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Crash Gold Rush",
		gameCode: "MultiPlayerCrashGR",
		gameImage: "MultiPlayerCrashGR.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerCrashGR', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Crash Classic",
		gameCode: "MultiPlayerCrashCL",
		gameImage: "MultiPlayerCrashCL.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerCrashCL', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Crash Neon",
		gameCode: "MultiPlayerCrashNE",
		gameImage: "MultiPlayerCrashNE.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerCrashNE', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Aviator",
		gameCode: "MultiPlayerAviator",
		gameImage: "MultiPlayerAviator.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerAviator', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 107,
		name: "Aviator2-Sky Elite",
		gameCode: "MultiPlayerAviator2",
		gameImage: "MultiPlayerAviator2.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/GEMINI/Desktop/MultiPlayerAviator2', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const AdvantPlayMiniGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 62,
		name: "Coming soon",
		gameCode: "Comingsoon",
		gameImage: "Comingsoon.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ADVANTPLAYMINIGAME/Desktop/Comingsoon', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashSpadeGaming: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 29,
		name: "Space Crasher",
		gameCode: "A-SC01",
		gameImage: "A-SC01.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SPADEGAMING/Desktop/A-SC01', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashOnlyPlayGames: Game[] = [
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "Gold of Baboon",
		gameCode: "goldofbaboon",
		gameImage: "goldofbaboon.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/goldofbaboon', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "F777 Fighter",
		gameCode: "fighter",
		gameImage: "fighter.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/fighter', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "Football Tap",
		gameCode: "footballtap",
		gameImage: "footballtap.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/footballtap', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "ScoreX",
		gameCode: "scorex",
		gameImage: "scorex.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/scorex', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "CricX",
		gameCode: "cricx",
		gameImage: "cricx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/cricx', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "GoalX",
		gameCode: "goalx",
		gameImage: "goalx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/goalx', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "Cricket Crash",
		gameCode: "cricketcrash",
		gameImage: "cricketcrash.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/cricketcrash', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash",
		categories: null,
		provider: 97,
		name: "CosmoX",
		gameCode: "cosmox",
		gameImage: "cosmox.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/ONLYPLAY/Desktop/cosmox', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashJokerGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 6,
		name: "Out Run",
		gameCode: "fxko1inijjfwo",
		gameImage: "fxko1inijjfwo.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/JOKER/Desktop/fxko1inijjfwo', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 6,
		name: "Nyan Cat",
		gameCode: "tt4ki7xk7xwq1",
		gameImage: "tt4ki7xk7xwq1.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/JOKER/Desktop/tt4ki7xk7xwq1', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 6,
		name: "Cash Or Crash",
		gameCode: "r43yaw4okfmfq",
		gameImage: "r43yaw4okfmfq.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/JOKER/Desktop/r43yaw4okfmfq', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashDragoonsoftGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 81,
		name: "Flying Phoenix",
		gameCode: "DRAGOONSOFT_4006",
		gameImage: "DRAGOONSOFT_4006.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/DRAGOONSOFT/Desktop/DRAGOONSOFT_4006', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 81,
		name: "Dragon or Crash",
		gameCode: "DRAGOONSOFT_4013",
		gameImage: "DRAGOONSOFT_4013.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/DRAGOONSOFT/Desktop/DRAGOONSOFT_4013', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const CrashFunkyGames: Game[] = [
	{
		category: "Crash Game",
		categories: null,
		provider: 35,
		name: "Cash Or Crash",
		gameCode: "FUNKYGAMES_16010002",
		gameImage: "FUNKYGAMES_16010002.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SBOFUNKYGAME/Desktop/FUNKYGAMES_16010002', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Crash Game",
		categories: null,
		provider: 35,
		name: "Midnight Robbery",
		gameCode: "FUNKYGAMES_228",
		gameImage: "FUNKYGAMES_228.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SBOFUNKYGAME/Desktop/FUNKYGAMES_228', 'CrashGame')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
