export const defaultItems: MarqueeItem[] = [
	{
		text: "🔥 Kesempatan Jakpot slots hari ini hingga IDR 102,550,000,00!",
		link: "/",
		urgent: true,
	},
	{
		text: "🔥 Exclusive pengguna baru & deposit pertama langsung dapat bonus 100%",
		link: "/",
	},
	{
		text: "🚚 Bonus saldo %50 untuk setiap deposit kelipatan ke 10 kalinya - Gunakan code: FREESHIP",
		link: "/",
	},
	{
		text: "⭐ Join our loyalty program and get 20% off your next purchase",
		link: "/",
	},
	{
		text: "🎉 Grand opening of our new store location in Jakarta!",
		link: "/",
	},
];
export const defaultCarouselItems: CarouselItem[] = [
	{
		image: "/images/carousels/banner-01.jpg",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-09.jpeg",
		link: "https://public.pg-demo.com/events/oct/zf039/?_gl=1%2aomxr0n%2a_ga%2aMjAxNjg2MjI0MS4xNzU5ODQ1MTUy%2a_ga_7F3F0R72T0%2aczE3NTk4NDUxNjkkbzEkZzEkdDE3NTk4NDc3NDUkajUxJGwwJGgw",
		alt: "Carousel slide 1",
		is_external: true,
	},
	{
		image: "/images/carousels/banner-11.jpg",
		link: "https://www.baoding68h.net/",
		alt: "Carousel slide 1",
		is_external: true,
	},
	{
		image: "/images/carousels/banner-02.jpg",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-03.png",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-04.png",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-05.jpg",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-07.png",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-08.jpg",
		link: "/",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-10.png",
		link: "/slots/hacksaw",
		alt: "Carousel slide 1",
		is_external: false,
	},
	{
		image: "/images/carousels/banner-10.png",
		link: "/slots/habanero",
		alt: "Carousel slide 1",
		is_external: false,
	},
];
export const defaultInnerSlides: CarouselInnerSlide[] = [
	{
		id: "1",
		title: "Pragmatic Play",
		description:
			"Pragmatic Play adalah salah satu pemain utama di dunia iGaming. Kami hadir dengan slot pemenang penghargaan, live casino, dan konten multi-produk yang ngasih performa maksimal dan bikin pemain terpikat di seluruh dunia. Dikenal karena inovasi, kualitas, dan gerak cepat—kami bukan cuma ikut tren, tapi yang bikin tren!",
		image: "/images/providers/game-code-7.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/pragmatic",
	},
	{
		id: "2",
		title: "PG Soft",
		description:
			"Didirikan di tahun 2015 dan berbasis di Malta, PG SOFT adalah perusahaan pertama yang mematenkan permainan seluler dalam format potret. Dengan kantor di seluruh dunia, timnya memiliki lebih dari 10 tahun pengalaman dalam Riset dan Pengembangan.",
		image: "/images/providers/game-code-9.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/pgsoft",
	},
	{
		id: "3",
		title: "Slot88 x PP",
		description:
			"Slot88 menghadirkan permainan slot yang sederhana dan menyenangkan, memberikan pengalaman seru bagi pemain yang mencari hiburan berkualitas dan gameplay yang mulus.",
		image: "/images/providers/game-code-40.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/slot88",
	},
	{
		id: "4",
		title: "Hacksaw",
		description:
			"Mobile friendly, inovatif, dan tema yang kuat - permainan slot kami dirancang untuk hiburan maksimal. Semua desain didasarkan pada layar vertikal untuk permainan yang dioptimalkan saat bepergian, permainan kami akan berfungsi pada setiap perangkat, semua smartphone, tablet, dan komputer desktop. Permainan kami tersedia di sebagian besar yurisdiksi yang diatur di seluruh dunia dan memiliki fitur seperti pembelian fitur, tingkat taruhan variabel, dan autoplay.",
		image: "/images/providers/game-code-98.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/hacksaw",
	},
	{
		id: "5",
		title: "Fat Panda",
		description:
			"Fat Panda adalah slot brand dari Pragmatic Play yang bold dan penuh impact! Dirancang buat nyita perhatian dan kasih gameplay seru yang nggak ketebak. Dengan energi yang meledak-ledak, visual yang kece, dan potensi menang besar—Fat Panda bukan cuma hiburan, tapi pembawa hoki sejati!",
		image: "/images/providers/game-code-112.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/fat-panda",
	},
	{
		id: "6",
		title: "No Limit City",
		description:
			"Dengan tema yang gelap, berani, dan sering kali provokatif, permainan Nolimit City menawarkan pengalaman yang benar-benar tak terlupakan bagi pemain di seluruh dunia yang suka mencoba sesuatu yang sedikit berbeda!",
		image: "/images/providers/game-code-92.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/no-limit-city",
	},
	{
		id: "7",
		title: "Jili",
		description:
			"Kami berkomitmen untuk menciptakan permainan terbaik dan orisinal dalam mencapai keunggulan dan inovasi, yang merupakan nilai inti kami. Kami merancang slot video online yang menarik dan permainan memancing, selalu berada di depan persaingan, dan merilis permainan inovatif.",
		image: "/images/providers/game-code-70.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/jili",
	},
	{
		id: "8",
		title: "Habanero",
		description:
			"Habanero menciptakan permainan slot dan permainan meja berkualitas untuk industri gaming. Cocok untuk operator dan agregator, game HTML5 kami yang mendukung berbagai bahasa dan mata uang merupakan pilihan tepat untuk pasar mana pun.",
		image: "/images/providers/game-code-16.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/habanero",
	},
	{
		id: "9",
		title: "MicroGaming",
		description:
			"Microgaming menghadirkan slot dan permainan live casino yang dirancang secara ahli, menghadirkan sensasi tanpa henti dan gameplay terpercaya",
		image: "/images/providers/game-code-17.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/microgaming",
	},
	{
		id: "10",
		title: "5GG",
		description:
			"Sebagai pengembang inovatif aplikasi seluler yang digamifikasi, kami menyediakan permainan paling canggih bagi pemain di seluruh dunia, dengan efek suara yang menakjubkan dan pengalaman visual yang tak terlupakan.",
		image: "/images/providers/game-code-114.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/fivegg",
	},
	{
		id: "11",
		title: "Playtech",
		description:
			"Jackpot giant adalah slot online dari Playtech dengan nuansa jaman batu dan tema prasejarah dengan fitur progressive jackpot dengan 50 pay lines dan 5 baris. Kumpulkanlah 3 tangan raksasa memegang uang untuk mengaktifkan fitur putaran gratis.",
		image: "/images/providers/game-code-2.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/playtech",
	},
	{
		id: "12",
		title: "Spade Gaming",
		description:
			"Spadegaming adalah pengembang game terkemuka yang dikenal karena beragam game kasino online yang inovatif. Didirikan di Asia, Spadegaming telah membangun reputasi kuat dalam menciptakan game slot yang menarik serta RNG lainnya seperti Crash Game, dan juga Fishing games, yang berhasil memikat pemain di seluruh dunia. Dengan komitmen kami terhadap konten berkualitas tinggi, tema-tema unik, dan pengalaman bermain yang superior, Spadegaming terus menghadirkan More Than Games untuk pemain kasual maupun berpengalaman.",
		image: "/images/providers/game-code-29.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/spade-gaming",
	},
	{
		id: "13",
		title: "King Midas",
		description:
			"Sejak 2018, KingMidas Games telah mendefinisikan ulang iGaming. Konten generasi berikutnya kami bukan hanya berbeda — tetapi juga transformasional, meningkatkan keterlibatan dan pendapatan bagi para mitra yang mencari inovasi dan hasil yang nyata.",
		image: "/images/providers/game-code-116.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/king-midas",
	},
	{
		id: "14",
		title: "Fast Spin",
		description:
			"FASTPIN mendefinisikan ulang dunia game melalui rilisan-rilisan yang kreatif dan berkualitas tinggi dengan memadukan inovasi dan desain, serta menghadirkan pengalaman bermain yang segar dan mendebarkan di setiap saat.",
		image: "/images/providers/game-code-110.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/fast-spin",
	},
	{
		id: "15",
		title: "VPLUS",
		description:
			"VPlus, berlisensi Malta, menawarkan slot dari klasik hingga jackpot, dengan bonus berbasis turnover dan hadiah misi baru untuk meningkatkan keterlibatan dan retensi pemain.",
		image: "/images/providers/game-code-115.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/vplus",
	},
	{
		id: "16",
		title: "Joker",
		description:
			"Kami tawarkan slot, memancing, bingo, funky &amp; e-game di H5 &amp; APP. Main fleksibel, dukungan 24/7, event seru &amp; hadiah keren bersama Joker!",
		image: "/images/providers/game-code-6.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/joker",
	},
	{
		id: "17",
		title: "Fachai",
		description:
			"FA CHAI didirikan pada 2019, menyajikan game bersertifikasi GLI dengan visual memukau &amp; gameplay unik dari Asia ke pasar global.",
		image: "/images/providers/game-code-72.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/fachai",
	},
	{
		id: "18",
		title: "AdvantPlay",
		description:
			"AdvantPlay, yang didirikan pada tahun 2020, adalah penyedia permainan generasi berikutnya yang menciptakan permainan kasino unik yang terinspirasi dari kehidupan nyata. Energi muda kami mendorong inovasi dan kreativitas, yang menarik pemain Gen Y. Dengan teknologi Provably Fair, kami memastikan permainan yang transparan dan dapat diverifikasi untuk semua orang.",
		image: "/images/providers/game-code-54.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/advantplay",
	},
	{
		id: "19",
		title: "Smartsoft",
		description:
			"Smartsoft Gaming adalah penyedia game Crash terkemuka yang menawarkan pengalaman bermain game berkualitas tinggi di seluruh dunia untuk memberikan pengalaman yang lebih menarik, menghibur, dan unggul.",
		image: "/images/providers/game-code-108.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/smartsoft",
	},
	{
		id: "20",
		title: "Naga Games",
		description:
			"Kami bertujuan untuk menjadi penyedia permainan slot kelas dunia dalam industri ini. Kami selalu berusaha untuk mendefinisikan ulang dan menghidupkan kembali permainan slot klasik, memberikan pengalaman bermain yang diperbarui kepada pengguna setiap kali bermain",
		image: "/images/providers/game-code-87.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/naga-games",
	},
	{
		id: "21",
		title: "JDB",
		description:
			"JDB Gaming—ahli terpercaya dalam permainan tembak ikan dan penyedia game dengan retensi tinggi untuk mitra yang mencari performa terbukti di iGaming!",
		image: "/images/providers/game-code-51.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/jdb",
	},
	{
		id: "22",
		title: "Playstar",
		description:
			"Dengan pengalaman puluhan tahun dan inovasi HTML5, PLAYSTAR mendefinisikan ulang permainan tradisional—menawarkan pengalaman yang halus dan beragam untuk memenuhi permintaan pasar",
		image: "/images/providers/game-code-65.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/playstar",
	},
	{
		id: "23",
		title: "Spinix",
		description:
			"SPINIX didirikan pada tahun 2020 oleh para pemain dengan hasrat untuk inovasi dalam pengalaman bermain game dan komitmen untuk membangun produk game kelas dunia. Dibangun oleh para pemain untuk para pemain",
		image: "/images/providers/game-code-91.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/spinix",
	},
	{
		id: "24",
		title: "Crowd Play",
		description:
			"CrowdPlay lahir dari cinta kami pada permainan, menghadirkan game terbaik dan inovasi interaksi pemain untuk mendorong pertumbuhan Anda di iGaming",
		image: "/images/providers/game-code-73.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/crowd-play",
	},
	{
		id: "25",
		title: "ION Slot",
		description:
			"ION SLOT adalah merek slot online terpercaya yang memberikan pengalaman dengan bayaran tinggi dan sensasi tinggi bagi para pemain di seluruh dunia. Dari reels klasik hingga petualangan bertema, setiap putaran menghadirkan kegembiraan!",
		image: "/images/providers/game-code-50.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/ion-slot",
	},
	{
		id: "26",
		title: "Bigpot",
		description:
			"Bigpot Gaming membangun permainan hebat, dan kami bertujuan melakukan segala yang kami bisa untuk merangsang pemain dengan lebih banyak kegembiraan dan antusiasme. Fitur yang paling dicintai oleh pemain ada di Bigpot Gaming",
		image: "/images/providers/game-code-75.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/bigpot",
	},
	{
		id: "27",
		title: "VPower",
		description:
			"Apakah Anda siap menjelajahi dan memainkan permainan undian terbaik yang datang dengan hadiah yang memuaskan? V-Power menggetarkan imajinasi liar Anda! Ini adalah platform di mana Anda dapat meningkatkan permainan Anda dengan bonus khusus yang meningkatkan peluang kemenangan Anda",
		image: "/images/providers/game-code-77.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/vpower",
	},
	{
		id: "28",
		title: "AMB Slot",
		description:
			"Askmeslot membangkitkan imajinasi iGaming dengan teknologi mutakhir dan pengalaman imersif yang membawa pemain melampaui masa depan dunia game",
		image: "/images/providers/game-code-61.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/amb-slot",
	},
	{
		id: "29",
		title: "Worldmatch",
		description:
			"Penyedia slot berbasis di Veneto, World Match, memiliki sejumlah pencapaian pertama di industri, terutama sebagai penyedia permainan pertama yang membuka markasnya di Malta. Pandangan masa depan yang visioner ini membuka jalan bagi perpustakaan beragam dengan lebih dari 300 permainan",
		image: "/images/providers/game-code-89.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/worldmatch",
	},
	{
		id: "30",
		title: "Octoplay",
		description:
			"Octoplay menciptakan permainan slot berkualitas tinggi yang menggabungkan fitur asli, desain menonjol, dan gameplay menarik untuk memberikan pengalaman pemain yang luar biasa",
		image: "/images/providers/game-code-109.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/octoplay",
	},
	{
		id: "31",
		title: "Mario Club",
		description:
			"Komunitas iGaming berorientasi AI yang PERTAMA dan mungkin satu-satunya di Asia, yang berdedikasi untuk mengumpulkan jutaan pemain game Asia dalam satu komunitas, dari mana saja, kapan saja, dengan perangkat apa pun!",
		image: "/images/providers/game-code-80.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/mario-club",
	},
	{
		id: "32",
		title: "Dragoonsoft",
		description:
			"Dragoon Soft adalah studio muda yang telah berada dalam industri game sejak tahun 2018. Fokusnya adalah pasar perjudian Asia, dengan mengumpulkan sekelompok profesional berpengalaman dan penggemar game, tim ini bertekad memberikan pemain petualangan paling menghibur dan memberikan hasil yang memuaskan",
		image: "/images/providers/game-code-81.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/dragoonsoft",
	},
	{
		id: "33",
		title: "Fun Gaming",
		description:
			"Funky Games, sebagai penyedia permainan kasino yang berbeda, berkomitmen untuk menawarkan pengalaman bermain yang unik, aman, dan menarik kepada pemain di seluruh dunia seperti tak ada yang lain",
		image: "/images/providers/game-code-35.webp",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/funky-games",
	},
	{
		id: "34",
		title: "Live22",
		image: "/images/providers/game-code-45.webp",
		description:
			"Live22 menghadirkan game slot berkualitas tinggi dengan alur cerita dan fitur PvP sosial yang membantu operator menarik pemain, menonjol, dan menjangkau pasar baru",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/live22",
	},
	{
		id: "35",
		image: "/images/providers/game-code-13.webp",
		title: "CQ9",
		description:
			"CQ9 berupaya memimpin industri dengan menciptakan permainan hiburan berkualitas tinggi, berkembang pesat melalui R&amp;D, dan menggunakan teknologi untuk memenuhi beragam kebutuhan pelanggan",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/cq9",
	},
	{
		id: "36",
		image: "/images/providers/game-code-97.webp",
		title: "Only Play",
		description:
			"Menciptakan permainan hari ini untuk pemain esok. Kami mengubah aturan pengembangan game dengan fokus pada pengalaman pemain dan bagaimana dapat ditingkatkan. Kreativitas menyentuh mekanika permainan dan alat, kami bereksperimen saat menciptakan permainan baru dan/atau mengembangkan fitur baru",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/only-play",
	},
	{
		id: "37",
		image: "/images/providers/game-code-94.webp",
		title: "Netent",
		description:
			"NetEnt adalah penyedia solusi permainan premium terkemuka untuk operator kasino online paling sukses di dunia. Kami telah menjadi pelopor sejati dalam menggerakkan pasar dengan permainan seru yang didukung oleh platform mutakhir kami",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/netent",
	},
	{
		id: "38",
		image: "/images/providers/game-code-95.webp",
		title: "Big Time Gaming",
		description:
			"Big Time Gaming membakar dunia slot online dengan mekanika permainan Megaways™ yang inovatif, memiliki basis penggemar yang kuat, dan judul slot yang sangat terkenal",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/big-time-gaming",
	},
	{
		id: "40",
		title: "Red Tiger",
		image: "/images/providers/game-code-93.webp",
		description:
			"Kami berkomitmen untuk membangun slot dan permainan meja terbaik di pasar. Setiap hari, kami mencari cara baru, inovatif, dan menyenangkan untuk menyeimbangkan seni dan ilmu desain permainan kasino",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/red-tiger",
	},
	{
		id: "41",
		title: "Skywind",
		image: "/images/providers/game-code-90.webp",
		description:
			"Dengan lebih dari 200 permainan dalam portofolio kami, jelas bahwa kami didorong oleh gairah kami untuk menciptakan pengalaman yang menarik dan memikat",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/skywind",
	},
	{
		id: "42",
		title: "Yggdrasil",
		image: "/images/providers/game-code-42.webp",
		description:
			"Yggdrasil menonjol dengan mekanisme slot yang inovatif, visual yang memukau, dan fokus yang kuat pada kepatuhan, menghadirkan permainan yang unik dan solusi operator yang tepercaya",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/yggdrasil",
	},
	{
		id: "43",
		title: "Play'n Go",
		image: "/images/providers/game-code-18.webp",
		description:
			"Play’n GO pelopori iGaming dengan konten tingkat atas, inovasi, dan lebih dari 400 permainan – melampaui batasan untuk memberikan pengalaman pemain yang tak terlupakan",
		buttonText: "Coba Sekarang",
		buttonLink: "/slots/playngo",
	},
];
export const partners: Partner[] = [
	{
		name: "Pragmatic Play",
		logo: "/images/partners/game-code-7.webp",
		logo_colored: "/images/partners/game-code-7-colored.webp",
		category: "slots",
		slug: "pragmatic",
		url: "/slots/pragmatic",
	},
	{
		name: "PG Soft",
		logo: "/images/partners/game-code-9.webp",
		logo_colored: "/images/partners/game-code-9-colored.webp",
		category: "slots",
		slug: "pgsoft",
		url: "/slots/pgsoft",
	},
	{
		name: "Slot88",
		logo: "/images/partners/game-code-40.webp",
		logo_colored: "/images/partners/game-code-40-colored.webp",
		category: "slots",
		slug: "slot88",
		url: "/slots/slot88",
	},
	{
		name: "Hacksaw Gaming",
		logo: "/images/partners/game-code-98.webp",
		logo_colored: "/images/partners/game-code-98-colored.webp",
		category: "slots",
		slug: "hacksaw",
		url: "/slots/hacksaw",
	},
	{
		name: "Fat Panda",
		logo: "/images/partners/game-code-112.webp",
		logo_colored: "/images/partners/game-code-112-colored.webp",
		category: "slots",
		slug: "fat-panda",
		url: "/slots/fat-panda",
	},
	{
		name: "Nolimit City",
		logo: "/images/partners/game-code-92.webp",
		logo_colored: "/images/partners/game-code-92-colored.webp",
		category: "slots",
		slug: "no-limit-city",
		url: "/slots/no-limit-city",
	},
	{
		name: "JILI",
		logo: "/images/partners/game-code-70.webp",
		logo_colored: "/images/partners/game-code-70-colored.webp",
		category: "slots",
		slug: "jili",
		url: "/slots/jili",
	},
	{
		name: "Habanero",
		logo: "/images/partners/game-code-16.webp",
		logo_colored: "/images/partners/game-code-16-colored.webp",
		category: "slots",
		slug: "habanero",
		url: "/slots/habanero",
	},
	{
		name: "Microgaming",
		url: "/slots/microgaming",
		logo: "/images/partners/game-code-17.webp",
		logo_colored: "/images/partners/game-code-72-colored.webp",
		category: "slots",
		slug: "microgaming",
	},
	{
		name: "5G Games",
		url: "/slots/fivegg",
		logo: "/images/partners/game-code-114.webp",
		logo_colored: "/images/partners/game-code-114-colored.webp",
		category: "slots",
		slug: "fivegg",
	},
	{
		name: "Playtech",
		url: "/slots/playtech",
		logo: "/images/partners/game-code-2.webp",
		logo_colored: "/images/partners/game-code-2-colored.webp",
		category: "slots",
		slug: "playtech",
	},
	{
		name: "Spade Gaming",
		url: "/slots/spade-gaming",
		logo: "/images/partners/game-code-29.webp",
		logo_colored: "/images/partners/game-code-29-colored.webp",
		category: "slots",
		slug: "spade-gaming",
	},
	{
		name: "King Midas",
		url: "/slots/king-midas",
		logo: "/images/partners/game-code-116.webp",
		logo_colored: "/images/partners/game-code-116-colored.webp",
		category: "slots",
		slug: "king-midas",
	},
	{
		name: "Fast Spin",
		url: "/slots/fast-spin",
		logo: "/images/partners/game-code-110.webp",
		logo_colored: "/images/partners/game-code-110-colored.webp",
		category: "slots",
		slug: "fast-spin",
	},
	{
		name: "V Plus",
		url: "/slots/vplus",
		logo: "/images/partners/game-code-115.webp",
		logo_colored: "/images/partners/game-code-115-colored.webp",
		category: "slots",
		slug: "vplus",
	},
	{
		name: "Joker",
		url: "/slots/joker",
		logo: "/images/partners/game-code-6.webp",
		logo_colored: "/images/partners/game-code-6-colored.webp",
		category: "slots",
		slug: "joker",
	},
	{
		name: "FA Chai",
		url: "/slots/fachai",
		logo: "/images/partners/game-code-72.webp",
		logo_colored: "/images/partners/game-code-72-colored.webp",
		category: "slots",
		slug: "fachai",
	},
	{
		name: "Advant Play",
		url: "/slots/advantplay",
		logo: "/images/partners/game-code-54.webp",
		logo_colored: "/images/partners/game-code-54-colored.webp",
		category: "slots",
		slug: "advantplay",
	},
	{
		name: "Smartsoft Gaming",
		url: "/slots/smartsoft",
		logo: "/images/partners/game-code-108.webp",
		logo_colored: "/images/partners/game-code-108-colored.webp",
		category: "slots",
		slug: "smartsoft",
	},
	{
		name: "Naga Games",
		url: "/slots/naga-games",
		logo: "/images/partners/game-code-87.webp",
		logo_colored: "/images/partners/game-code-87-colored.webp",
		category: "slots",
		slug: "naga-games",
	},
	{
		name: "JDB",
		url: "/slots/jdb",
		logo: "/images/partners/game-code-51.webp",
		logo_colored: "/images/partners/game-code-51-colored.webp",
		category: "slots",
		slug: "jdb",
	},
	{
		name: "Play Star",
		url: "/slots/playstar",
		logo: "/images/partners/game-code-65.webp",
		logo_colored: "/images/partners/game-code-65-colored.webp",
		category: "slots",
		slug: "playstar",
	},
	{
		name: "SpinX",
		url: "/slots/spinix",
		logo: "/images/partners/game-code-91.webp",
		logo_colored: "/images/partners/game-code-91-colored.webp",
		category: "slots",
		slug: "spinix",
	},
	{
		name: "Crowd Play",
		url: "/slots/crowd-play",
		logo: "/images/partners/game-code-73.webp",
		logo_colored: "/images/partners/game-code-73-colored.webp",
		category: "slots",
		slug: "crowd-play",
	},
	{
		name: "Ion Slot",
		url: "/slots/ion-slot",
		logo: "/images/partners/game-code-50.webp",
		logo_colored: "/images/partners/game-code-50-colored.webp",
		category: "slots",
		slug: "ion-slot",
	},
	{
		name: "Bigpot Gaming",
		url: "/slots/bigpot",
		logo: "/images/partners/game-code-75.webp",
		logo_colored: "/images/partners/game-code-75-colored.webp",
		category: "slots",
		slug: "bigpot",
	},
	{
		name: "KA Gaming",
		url: "/slots/vpower",
		logo: "/images/partners/game-code-77.webp",
		logo_colored: "/images/partners/game-code-77-colored.webp",
		category: "slots",
		slug: "vpower",
	},
	{
		name: "Askmebet",
		url: "/slots/amb-slot",
		logo: "/images/partners/game-code-61.webp",
		logo_colored: "/images/partners/game-code-61-colored.webp",
		category: "slots",
		slug: "amb-slot",
	},
	{
		name: "WorldMatch",
		url: "/slots/worldmatch",
		logo: "/images/partners/game-code-89.webp",
		logo_colored: "/images/partners/game-code-89-colored.webp",
		category: "slots",
		slug: "worldmatch",
	},
	{
		name: "Octoplay",
		url: "/slots/octoplay",
		logo: "/images/partners/game-code-109.webp",
		logo_colored: "/images/partners/game-code-109-colored.webp",
		category: "slots",
		slug: "octoplay",
	},
	{
		name: "Mario Club",
		url: "/slots/mario-club",
		logo: "/images/partners/game-code-80.webp",
		logo_colored: "/images/partners/game-code-80-colored.webp",
		category: "slots",
		slug: "mario-club",
	},
	{
		name: "Dragoon Soft",
		url: "/slots/dragoonsoft",
		logo: "/images/partners/game-code-81.webp",
		logo_colored: "/images/partners/game-code-81-colored.webp",
		category: "slots",
		slug: "dragoonsoft",
	},
	{
		name: "FG Games",
		url: "/slots/fun-gaming",
		logo: "/images/partners/game-code-79.webp",
		logo_colored: "/images/partners/game-code-79-colored.webp",
		category: "slots",
		slug: "fun-gaming",
	},
	{
		name: "Funky Games",
		url: "/slots/funky-games",
		logo: "/images/partners/game-code-35.webp",
		logo_colored: "/images/partners/game-code-35-colored.webp",
		category: "slots",
		slug: "funky-games",
	},
	{
		name: "Live22",
		url: "/slots/live22",
		logo: "/images/partners/game-code-45.webp",
		logo_colored: "/images/partners/game-code-45-colored.webp",
		category: "slots",
		slug: "live22",
	},
	{
		name: "CQ9",
		url: "/slots/cq9",
		logo: "/images/partners/game-code-13.webp",
		logo_colored: "/images/partners/game-code-13-colored.webp",
		category: "slots",
		slug: "cq9",
	},
	{
		name: "Onlyplay",
		url: "/slots/only-play",
		logo: "/images/partners/game-code-97.webp",
		logo_colored: "/images/partners/game-code-97-colored.webp",
		category: "slots",
		slug: "only-play",
	},
	{
		name: "NetEnt",
		url: "/slots/netent",
		logo: "/images/partners/game-code-94.webp",
		logo_colored: "/images/partners/game-code-94-colored.webp",
		category: "slots",
		slug: "netent",
	},
	{
		name: "BigTime Gaming",
		url: "/slots/big-time-gaming",
		logo: "/images/partners/game-code-95.webp",
		logo_colored: "/images/partners/game-code-95-colored.webp",
		category: "slots",
		slug: "big-time-gaming",
	},
	{
		name: "Red Tiger",
		url: "/slots/red-tiger",
		logo: "/images/partners/game-code-93.webp",
		logo_colored: "/images/partners/game-code-93-colored.webp",
		category: "slots",
		slug: "red-tiger",
	},
	{
		name: "Skywind Group",
		url: "/slots/skywind",
		logo: "/images/partners/game-code-90.webp",
		logo_colored: "/images/partners/game-code-90-colored.webp",
		category: "slots",
		slug: "skywind",
	},
	{
		name: "Yggdrasil",
		url: "/slots/yggdrasil",
		logo: "/images/partners/game-code-42.webp",
		logo_colored: "/images/partners/game-code-42-colored.webp",
		category: "slots",
		slug: "yggdrasil",
	},
	{
		name: "Play'n GO",
		url: "/slots/playngo",
		logo: "/images/partners/game-code-18.webp",
		logo_colored: "/images/partners/game-code-18-colored.webp",
		category: "slots",
		slug: "playngo",
	},
];
export const defaultPopularGames: Game[] = [
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 4,
			},
			{
				name: "Video Slots",
				seqNo: 21,
			},
			{
				name: "DEFAULT",
				seqNo: 22,
			},
		],
		provider: 0,
		name: "Sweet Bonanza Super Scatter",
		gameCode: "vs20swbonsup",
		gameImage: "vs20swbonsup.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20swbonsup', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 1,
			},
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "Video Slots",
				seqNo: -1,
			},
			{
				name: "DEFAULT",
				seqNo: 16,
			},
		],
		provider: 0,
		name: "Mahjong Ways",
		gameCode: "PGSOFT_65",
		gameImage: "PGSOFT_65.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PGSOFT/Desktop/PGSOFT_65', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 3,
			},
			{
				name: "Video Slots",
				seqNo: 480,
			},
			{
				name: "DEFAULT",
				seqNo: 117,
			},
		],
		provider: 0,
		name: "Mahjong Wins 3 – Black Scatter",
		gameCode: "vswaysmahwblck",
		gameImage: "vswaysmahwblck.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vswaysmahwblck', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Slots",
		categories: [
			{
				name: "Top 20",
				seqNo: 2,
			},
			{
				name: "Slots",
				seqNo: 2,
			},
			{
				name: "DEFAULT",
				seqNo: 933,
			},
		],
		provider: 0,
		name: "Wukong - Black Scatter",
		gameCode: "vswayswkngblck",
		gameImage: "vswayswkngblck.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SLOT88/Desktop/vswayswkngblck', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 1,
			},
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "New Games",
				seqNo: 1,
			},
			{
				name: "Classic Games",
				seqNo: -1,
			},
			{
				name: "Bonus Buy",
				seqNo: 1,
			},
			{
				name: "Jackpot Games",
				seqNo: -1,
			},
			{
				name: "DEFAULT",
				seqNo: 2700,
			},
		],
		provider: 0,
		name: "Sticky Bandits Thunder Rail",
		gameCode: "pop_001378cc_qsp",
		gameImage: "pop_001378cc_qsp.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PLAYTECH/Desktop/pop_001378cc_qsp', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Slots",
		categories: [
			{
				name: "Top 20",
				seqNo: 3,
			},
			{
				name: "Slots",
				seqNo: 3,
			},
			{
				name: "DEFAULT",
				seqNo: 1151,
			},
		],
		provider: 0,
		name: "Bang Gacor 1000",
		gameCode: "vs20gacorx",
		gameImage: "vs20gacorx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SLOT88/Desktop/vs20gacorx', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "Slots",
				seqNo: 31,
			},
			{
				name: "DEFAULT",
				seqNo: 5603,
			},
		],
		provider: 0,
		name: "Sugar Bang Bang 2",
		gameCode: "FACAHI_22071",
		gameImage: "FACAHI_22071.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/FACHAI/Desktop/FACAHI_22071', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 9,
			},
			{
				name: "DEFAULT",
				seqNo: 370,
			},
		],
		provider: 0,
		name: "Fortune Gems",
		gameCode: "JILI_109",
		gameImage: "JILI_109.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/JILI/Desktop/JILI_109', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 2,
			},
			{
				name: "DEFAULT",
				seqNo: 23,
			},
		],
		provider: 0,
		name: "Mahjong Ways 2",
		gameCode: "PGSOFT_74",
		gameImage: "PGSOFT_74.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PGSOFT/Desktop/PGSOFT_74', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 2,
			},
			{
				name: "Video Slots",
				seqNo: 36,
			},
			{
				name: "DEFAULT",
				seqNo: 79,
			},
		],
		provider: 0,
		name: "Gates of Olympus Super Scatter",
		gameCode: "vs20olympgold",
		gameImage: "vs20olympgold.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20olympgold', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 3,
			},
			{
				name: "DEFAULT",
				seqNo: 67,
			},
		],
		provider: 0,
		name: "Wild Bounty Showdown",
		gameCode: "PGSOFT_135",
		gameImage: "PGSOFT_135.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PGSOFT/Desktop/PGSOFT_135', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 4,
			},
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "Bonus Buy Feature",
				seqNo: 22,
			},
			{
				name: "MEGAWays",
				seqNo: -1,
			},
			{
				name: "Fixed Jackpot",
				seqNo: -1,
			},
			{
				name: "Video Slots",
				seqNo: 184,
			},
			{
				name: "DEFAULT",
				seqNo: 12,
			},
		],
		provider: 0,
		name: "Lucky Twins Nexus",
		gameCode: "SMG_luckyTwinsNexus",
		gameImage: "SMG_luckyTwinsNexus.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MICROGAMING/Desktop/SMG_luckyTwinsNexus', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 1,
			},
			{
				name: "Top 20",
				seqNo: -1,
			},
			{
				name: "New",
				seqNo: -1,
			},
			{
				name: "Classic",
				seqNo: -1,
			},
			{
				name: "Bonus Buy",
				seqNo: 53,
			},
			{
				name: "Reel kingdom",
				seqNo: -1,
			},
			{
				name: "Megaways",
				seqNo: -1,
			},
			{
				name: "Jackpot Play Games",
				seqNo: -1,
			},
			{
				name: "Video Slots",
				seqNo: 541,
			},
			{
				name: "DEFAULT",
				seqNo: 18,
			},
		],
		provider: 0,
		name: "Gates of Olympus 1000",
		gameCode: "vs20olympx",
		gameImage: "vs20olympx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20olympx', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 1,
			},
			{
				name: "DEFAULT",
				seqNo: 2811,
			},
		],
		provider: 0,
		name: "Nexus Koi Gate",
		gameCode: "SGNexusKoiGate",
		gameImage: "SGNexusKoiGate.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/HABANERO/Desktop/SGNexusKoiGate', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 12,
			},
			{
				name: "DEFAULT",
				seqNo: 351,
			},
		],
		provider: 0,
		name: "The Crypt",
		gameCode: "thecrypt00000000",
		gameImage: "thecrypt00000000.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/NOLIMITCITY/Desktop/thecrypt00000000', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 1,
			},
			{
				name: "Video Slots",
				seqNo: 22,
			},
			{
				name: "DEFAULT",
				seqNo: 62,
			},
		],
		provider: 0,
		name: "Nexus Mahjong Jackpots",
		gameCode: "SMG_nexusMahjongJackpots",
		gameImage: "SMG_nexusMahjongJackpots.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MICROGAMING/Desktop/SMG_nexusMahjongJackpots', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Slots",
		categories: [
			{
				name: "Slots",
				seqNo: 3,
			},
			{
				name: "DEFAULT",
				seqNo: 84,
			},
		],
		provider: 0,
		name: "Fire in the Hole 3",
		gameCode: "fireinthehole300",
		gameImage: "fireinthehole300.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/NOLIMITCITY/Desktop/fireinthehole300', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 2,
			},
			{
				name: "Video Slots",
				seqNo: 2,
			},
			{
				name: "DEFAULT",
				seqNo: 2971,
			},
		],
		provider: 0,
		name: "777 Rush",
		gameCode: "vs5t8goldfp",
		gameImage: "vs5t8goldfp.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/FATPANDA/Desktop/vs5t8goldfp', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 5,
			},
			{
				name: "DEFAULT",
				seqNo: 3071,
			},
		],
		provider: 0,
		name: "Hot Hot Nexus",
		gameCode: "SGHotHotNexus",
		gameImage: "SGHotHotNexus.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/HABANERO/Desktop/SGHotHotNexus', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "New",
		categories: [
			{
				name: "Slots",
				seqNo: 69,
			},
			{
				name: "New",
				seqNo: 31,
			},
			{
				name: "DEFAULT",
				seqNo: 1236,
			},
		],
		provider: 0,
		name: "Le Pharaoh",
		gameCode: "HACKSAW_1562",
		gameImage: "HACKSAW_1562.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/HACKSAW/Desktop/HACKSAW_1562', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top",
		categories: [
			{
				name: "Top 20",
				seqNo: 5,
			},
			{
				name: "Bonus Buy",
				seqNo: 3,
			},
			{
				name: "Video Slots",
				seqNo: 219,
			},
			{
				name: "DEFAULT",
				seqNo: 149,
			},
		],
		provider: 0,
		name: "Starlight Princess™ 1000",
		gameCode: "vs20starlightx",
		gameImage: "vs20starlightx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20starlightx', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top",
		categories: [
			{
				name: "Top 20",
				seqNo: 9,
			},
			{
				name: "Bonus Buy",
				seqNo: 75,
			},
			{
				name: "Video Slots",
				seqNo: 88,
			},
			{
				name: "DEFAULT",
				seqNo: 221,
			},
		],
		provider: 0,
		name: "Gates of Gatot Kaca 1000",
		gameCode: "vs20gatotx",
		gameImage: "vs20gatotx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20gatotx', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top",
		categories: [
			{
				name: "Bonus Buy",
				seqNo: 55,
			},
			{
				name: "Video Slots",
				seqNo: 288,
			},
			{
				name: "DEFAULT",
				seqNo: 248,
			},
		],
		provider: 0,
		name: "Sweet Bonanza",
		gameCode: "vs20fruitsw",
		gameImage: "vs20fruitsw.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20fruitsw', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Top 20",
		categories: [
			{
				name: "Top 20",
				seqNo: 10,
			},
			{
				name: "Bonus Buy",
				seqNo: 57,
			},
			{
				name: "Video Slots",
				seqNo: 515,
			},
			{
				name: "DEFAULT",
				seqNo: 252,
			},
		],
		provider: 0,
		name: "Sugar Rush 1000",
		gameCode: "vs20sugarrushx",
		gameImage: "vs20sugarrushx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20sugarrushx', 'Slots')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
export const trendingGameItems = [
	{
		id: "1",
		title: "Gates of Olympus Super Scatter",
		subtitle: "sgtrai****1",
		amount: "IDR 710,000.00",
		gameCode: "vs20olympgold",
		gameImage: "vs20olympgold.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20olympgold', 'Slots')",
	},
	{
		id: "2",
		title: "Sweet Bonanza Xmas",
		subtitle: "lucky***88",
		amount: "IDR 850,000.00",
		gameCode: "vs20sbxmas",
		gameImage: "vs20sbxmas.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20sbxmas', 'Slots')",
	},
	{
		id: "3",
		title: "Starlight Princess Power",
		subtitle: "winner**21",
		amount: "IDR 1,200,000.00",
		gameCode: "vs20slot88spx",
		gameImage: "vs20slot88spx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/SLOT88/Desktop/vs20slot88spx', 'Slots')",
	},
	{
		id: "4",
		title: "Aztec Gems Deluxe",
		subtitle: "jackpot**99",
		amount: "IDR 650,000.00",
		gameCode: "vs9aztecgemsdx",
		gameImage: "vs9aztecgemsdx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs9aztecgemsdx', 'Slots')",
	},
	{
		id: "5",
		title: "Wild West Gold",
		subtitle: "cowboy**77",
		amount: "IDR 920,000.00",
		gameCode: "vs40wildwest",
		gameImage: "vs40wildwest.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs40wildwest', 'Slots')",
	},
	{
		id: "6",
		title: "Sugar Rush 1000",
		subtitle: "hadi**86",
		amount: "IDR 1,080,000.00",
		gameCode: "vs20sugarrushx",
		gameImage: "vs20sugarrushx.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vs20sugarrushx', 'Slots')",
	},
	{
		id: "6",
		title: "Mahjong Wins - Gong Xi Fa Cai",
		subtitle: "jamal**02",
		amount: "IDR 2,130,000.00",
		gameCode: "vswaysmahwgong",
		gameImage: "vswaysmahwgong.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vswaysmahwgong', 'Slots')",
	},
	{
		id: "7",
		title: "Sweet Bonanza Xmas",
		subtitle: "nbere**05",
		amount: "IDR 652,000.00",
		gameCode: "vswaysmahwgong",
		gameImage: "vswaysmahwgong.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/PP/Desktop/vswaysmahwgong', 'Slots')",
	},
];
