export const RaceMarblexGames: Game[] = [
	{
		category: "Race",
		categories: null,
		provider: 0,
		name: "Tokyo Drift Nitro",
		gameCode: "MarbleX_1101",
		gameImage: "MarbleX_1101.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MARBLEX/Desktop/MarbleX_1101', 'Race')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Race",
		categories: null,
		provider: 0,
		name: "Tokyo Drift",
		gameCode: "MarbleX_1001",
		gameImage: "MarbleX_1001.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MARBLEX/Desktop/MarbleX_1001', 'Race')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
	{
		category: "Race",
		categories: null,
		provider: 0,
		name: "Tommorow Land",
		gameCode: "MarbleX_2001",
		gameImage: "MarbleX_2001.jpg?v=20250528",
		link: "javascript:openNewTab('/dispatch/game/MARBLEX/Desktop/MarbleX_2001', 'Race')",
		isFavourite: false,
		rtpValue: null,
		rtpChanged: null,
	},
];
